INSERT INTO high_school (name, description, city_province_id)
VALUES ('Trường Phổ thông Năng Khiếu, Đại học Quốc gia TP.HCM', NULL, 58),
       ('Trường THPT chuyên Trần Đại Nghĩa', NULL, 58),
       ('Trường THPT chuyên Lê Hồng Phong', NULL, 58),
       ('Trường THPT Gia Định', NULL, 58),
       ('Trường THPT Mạc Đĩnh Chi', NULL, 58),
       ('Trường THPT Nguyễn Hữu Huân', NULL, 58),
       ('Trường THPT Nguyễn Thượng Hiền', NULL, 58),
       ('Trường THPT Năng khiếu Thể dục Thể thao TP.HCM', NULL, 58),
       ('Trường THPT Năng khiếu Thể dục Thể thao Nguyễn Thị Định', NULL, 58),
       ('Trường Phổ thông Năng khiếu Thể thao Olympic – Đại học Thể dục Thể thao TP.HCM', NULL, 58),
       ('Trường THPT Năng khiếu Thể dục Thể thao Bình Chánh', NULL, 58),
       ('Trường THPT Bùi Thị Xuân', NULL, 58),
       ('Trường THPT Trưng Vương', NULL, 58),
       ('Trường THPT Ernst Thälmann (Ten Lơ Man)', NULL, 58),
       ('Trường THPT Lương Thế Vinh', NULL, 58),
       ('Trường THPT Lê Quý Đôn', NULL, 58),
       ('Trường THPT Nguyễn Thị Minh Khai', NULL, 58),
       ('Trường THPT Marie Curie', NULL, 58),
       ('Trường THPT Nguyễn Thị Diệu', NULL, 58),
       ('Trường THPT Lê Thị Hồng Gấm', NULL, 58),
       ('Trường THPT Nguyễn Trãi', NULL, 58),
       ('Trường THPT Nguyễn Hữu Thọ', NULL, 58),
       ('Trường THPT Hùng Vương', NULL, 58),
       ('Trường Trung học Thực hành Sài Gòn', NULL, 58),
       ('Trường Trung học Thực hành - Đại học Sư phạm TP.HCM', NULL, 58),
       ('Trường THPT Trần Khai Nguyên', NULL, 58),
       ('Trường THPT chuyên Hà Nội - Amsterdam', NULL, 24),
       ('Trường THPT chuyên Nguyễn Huệ', NULL, 24),
       ('Trường THPT Chuyên Đại học Sư phạm Hà Nội', NULL, 24),
       ('Trường THPT chuyên Ngoại ngữ', NULL, 24),
       ('Trường THPT chuyên Khoa học Tự nhiên', NULL, 24),
       ('Trường THPT chuyên Khoa học Xã hội và Nhân văn', NULL, 24),
       ('Trường THPT Chu Văn An', NULL, 24),
       ('Trường THPT Sơn Tây', NULL, 24),
       ('Trường THPT Phan Đình Phùng', NULL, 24),
       ('Trường THPT Phạm Hồng Thái', NULL, 24),
       ('Trường THPT Nguyễn Trãi - Ba Đình', NULL, 24),
       ('Trường THPT Tây Hồ', NULL, 24),
       ('Trường THPT Chu Văn An', NULL, 24),
       ('Trường THPT Trần Phú - Hoàn Kiếm', NULL, 24),
       ('Trường THPT Việt Đức', NULL, 24),
       ('Trường THPT Thăng Long', NULL, 24),
       ('Trường THPT Trần Nhân Tông', NULL, 24),
       ('Trường THPT Đoàn Kết - Hai Bà Trưng', NULL, 24),
       ('Trường THPT Kim Liên', NULL, 24),
       ('Trường THPT Đống Đa', NULL, 24),
       ('Trường THPT Quang Trung - Đống Đa', NULL, 24),
       ('Trường THPT Lê Quý Đôn - Đống Đa', NULL, 24),
       ('Trường THPT Trần Hưng Đạo - Thanh Xuân', NULL, 24),
       ('Trường THPT Nhân Chính', NULL, 24);