INSERT INTO city_province (name)
VALUES ('An Giang'),
       ('Bà rịa Vũng Tàu'),
       ('Bạc Liêu'),
       ('Bắc Giang'),
       ('Bắc Kạn'),
       ('Bắc Ninh'),
       ('Bến Tre'),
       ('Bình Dương'),
       ('Bình Định'),
       ('Bình Phước'),
       ('Bình Thuận'),
       ('Cà Mau'),
       ('Cao Bằng'),
       ('Cần Thơ'),
       ('Đà Nẵng'),
       ('Đắk Lắk'),
       ('Đắk Nông'),
       ('Điện Biên'),
       ('Đồng Nai'),
       ('Đồng Tháp'),
       ('Gia Lai'),
       ('Hà Giang'),
       ('Hà Nam'),
       ('Hà Nội'),
       ('Hà Tĩnh'),
       ('Hải Dương'),
       ('Hải Phòng'),
       ('Hậu Giang'),
       ('Hòa Bình'),
       ('Hưng Yên'),
       ('Khánh Hòa'),
       ('Kiên Giang'),
       ('Kon Tum'),
       ('Lai Châu'),
       ('Lạng Sơn'),
       ('Lào Cai'),
       ('Lâm Đồng'),
       ('Long An'),
       ('Nam Định'),
       ('Nghệ An'),
       ('Ninh Bình'),
       ('Ninh Thuận'),
       ('Phú Thọ'),
       ('Phú Yên'),
       ('Quảng Bình'),
       ('Quảng Nam'),
       ('Quảng Ngãi'),
       ('Quảng Ninh'),
       ('Quảng Trị'),
       ('Sóc Trăng'),
       ('Sơn La'),
       ('Tây Ninh'),
       ('Thái Bình'),
       ('Thái Nguyên'),
       ('Thanh Hóa'),
       ('Thừa Thiên Huế'),
       ('Tiền Giang'),
       ('TP. Hồ Chí Minh'),
       ('Trà Vinh'),
       ('Tuyên Quang'),
       ('Vĩnh Long'),
       ('Vĩnh Phúc'),
       ('Yên Bái');

INSERT INTO district (name, city_province_id)
VALUES ('Thành phố Thủ Đức', 58),
       ('Quận 1', 58),
       ('Quận 3', 58),
       ('Quận 4', 58),
       ('Quận 5', 58),
       ('Quận 6', 58),
       ('Quận 7', 58),
       ('Quận 8', 58),
       ('Quận 10', 58),
       ('Quận 11', 58),
       ('Quận 12', 58),
       ('Quận Bình Tân', 58),
       ('Quận Bình Thạnh', 58),
       ('Quận Gò Vấp', 58),
       ('Quận Phú Nhuận', 58),
       ('Quận Tân Bình', 58),
       ('Quận Tân Phú', 58),
       ('Huyện Bình Chánh', 58),
       ('Huyện Cần Giờ', 58),
       ('Huyện Củ Chi', 58),
       ('Huyện Hóc Môn', 58),
       ('Huyện Nhà Bè', 58);

INSERT INTO district (name, city_province_id)
VALUES ('Quận Ba Đình', 24),
       ('Quận Cầu Giấy', 24),
       ('Quận Hoàn Kiếm', 24),
       ('Quận Hai Bà Trưng', 24),
       ('Quận Hoàng Mai', 24),
       ('Quận Đống Đa', 24),
       ('Quận Tây Hồ', 24),
       ('Quận Thanh Xuân', 24),
       ('Quận Bắc Từ Liêm', 24),
       ('Quận Hà Đông', 24),
       ('Quận Long Biên', 24),
       ('Quận Nam Từ Liêm', 24),
       ('Huyện Ba Vì', 24),
       ('Huyện Chương Mỹ', 24),
       ('Huyện Đan Phượng', 24),
       ('Huyện Đông Anh', 24),
       ('Huyện Gia Lâm', 24),
       ('Huyện Hoài Đức', 24),
       ('Huyện Mê Linh', 24),
       ('Huyện Mỹ Đức', 24),
       ('Huyện Phú Xuyên', 24),
       ('Huyện Phúc Thọ', 24),
       ('Huyện Quốc Oai', 24),
       ('Huyện Sóc Sơn', 24),
       ('Huyện Thạch Thất', 24),
       ('Huyện Thanh Oai', 24),
       ('Huyện Thanh Trì', 24),
       ('Huyện Thường Tín', 24),
       ('Huyện Ứng Hòa', 24),
       ('Thị xã Sơn Tây', 24);

INSERT INTO ward (name, district_id)
VALUES ('Phường An Khánh', 1),
       ('Phường An Lợi Đông', 1),
       ('Phường An Phú', 1),
       ('Phường Bình Chiểu', 1),
       ('Phường Bình Thọ', 1),
       ('Phường Bình Trưng Đông', 1),
       ('Phường Bình Trưng Tây', 1),
       ('Phường Cát Lái', 1),
       ('Phường Hiệp Bình Chánh', 1),
       ('Phường Hiệp Bình Phước', 1),
       ('Phường Hiệp Phú', 1),
       ('Phường Linh Chiểu', 1),
       ('Phường Linh Đông', 1),
       ('Phường Linh Tây', 1),
       ('Phường Linh Trung', 1),
       ('Phường Linh Xuân', 1),
       ('Phường Long Bình', 1),
       ('Phường Long Phước', 1),
       ('Phường Long Thạnh Mỹ', 1),
       ('Phường Long Trường', 1),
       ('Phường Phú Hữu', 1),
       ('Phường Phước Bình', 1),
       ('Phường Phước Long A', 1),
       ('Phường Phước Long B', 1),
       ('Phường Tam Bình', 1),
       ('Phường Tam Phú', 1),
       ('Phường Tăng Nhơn Phú A', 1),
       ('Phường Tăng Nhơn Phú B', 1),
       ('Phường Tân Phú', 1),
       ('Phường Thảo Điền', 1),
       ('Phường Thạnh Mỹ Lợi', 1),
       ('Phường Thủ Thiêm', 1),
       ('Phường Trường Thạnh', 1),
       ('Phường Trường Thọ', 1),
       ('Phường Bến Nghé', 2),
       ('Phường Bến Thành', 2),
       ('Phường Cầu Kho', 2),
       ('Phường Cầu Ông Lãnh', 2),
       ('Phường Cô Giang', 2),
       ('Phường Đa Kao', 2),
       ('Phường Nguyễn Cư Trinh', 2),
       ('Phường Nguyễn Thái Bình', 2),
       ('Phường Phạm Ngũ Lão', 2),
       ('Phường Tân Định', 2),
       ('Phường 01', 3),
       ('Phường 02', 3),
       ('Phường 03', 3),
       ('Phường 04', 3),
       ('Phường 05', 3),
       ('Phường Võ Thị Sáu', 3),
       ('Phường 09', 3),
       ('Phường 10', 3),
       ('Phường 11', 3),
       ('Phường 12', 3),
       ('Phường 13', 3),
       ('Phường 14', 3),
       ('Phường 01', 4),
       ('Phường 02', 4),
       ('Phường 03', 4),
       ('Phường 04', 4),
       ('Phường 06', 4),
       ('Phường 08', 4),
       ('Phường 09', 4),
       ('Phường 10', 4),
       ('Phường 13', 4),
       ('Phường 14', 4),
       ('Phường 15', 4),
       ('Phường 16', 4),
       ('Phường 18', 4),
       ('Phường 01', 5),
       ('Phường 02', 5),
       ('Phường 03', 5),
       ('Phường 04', 5),
       ('Phường 05', 5),
       ('Phường 06', 5),
       ('Phường 07', 5),
       ('Phường 08', 5),
       ('Phường 09', 5),
       ('Phường 10', 5),
       ('Phường 11', 5),
       ('Phường 12', 5),
       ('Phường 13', 5),
       ('Phường 14', 5),
       ('Phường 01', 6),
       ('Phường 02', 6),
       ('Phường 03', 6),
       ('Phường 04', 6),
       ('Phường 05', 6),
       ('Phường 06', 6),
       ('Phường 07', 6),
       ('Phường 08', 6),
       ('Phường 09', 6),
       ('Phường 10', 6),
       ('Phường 11', 6),
       ('Phường 12', 6),
       ('Phường 13', 6),
       ('Phường 14', 6),
       ('Phường Bình Thuận', 7),
       ('Phường Phú Mỹ', 7),
       ('Phường Phú Thuận', 7),
       ('Phường Tân Hưng', 7),
       ('Phường Tân Kiểng', 7),
       ('Phường Tân Phong', 7),
       ('Phường Tân Phú', 7),
       ('Phường Tân Quy', 7),
       ('Phường Tân Thuận Đông', 7),
       ('Phường Tân Thuận Tây', 7),
       ('Phường 01', 8),
       ('Phường 02', 8),
       ('Phường 03', 8),
       ('Phường 04', 8),
       ('Phường 05', 8),
       ('Phường 06', 8),
       ('Phường 07', 8),
       ('Phường 08', 8),
       ('Phường 09', 8),
       ('Phường 10', 8),
       ('Phường 11', 8),
       ('Phường 12', 8),
       ('Phường 13', 8),
       ('Phường 14', 8),
       ('Phường 15', 8),
       ('Phường 16', 8),
       ('Phường 01', 9),
       ('Phường 02', 9),
       ('Phường 04', 9),
       ('Phường 05', 9),
       ('Phường 06', 9),
       ('Phường 07', 9),
       ('Phường 08', 9),
       ('Phường 09', 9),
       ('Phường 10', 9),
       ('Phường 11', 9),
       ('Phường 12', 9),
       ('Phường 13', 9),
       ('Phường 14', 9),
       ('Phường 15', 9),
       ('Phường 01', 10),
       ('Phường 02', 10),
       ('Phường 03', 10),
       ('Phường 04', 10),
       ('Phường 05', 10),
       ('Phường 06', 10),
       ('Phường 07', 10),
       ('Phường 08', 10),
       ('Phường 09', 10),
       ('Phường 10', 10),
       ('Phường 11', 10),
       ('Phường 12', 10),
       ('Phường 13', 10),
       ('Phường 14', 10),
       ('Phường 15', 10),
       ('Phường 16', 10),
       ('Phường An Phú Đông', 11),
       ('Phường Đông Hưng Thuận', 11),
       ('Phường Hiệp Thành', 11),
       ('Phường Tân Chánh Hiệp', 11),
       ('Phường Tân Hưng Thuận', 11),
       ('Phường Tân Thới Hiệp', 11),
       ('Phường Tân Thới Nhất', 11),
       ('Phường Thạnh Lộc', 11),
       ('Phường Thạnh Xuân', 11),
       ('Phường Thới An', 11),
       ('Phường Trung Mỹ Tây', 11),
       ('Phường An Lạc', 12),
       ('Phường An Lạc A', 12),
       ('Phường Bình Hưng Hòa', 12),
       ('Phường Bình Hưng Hoà A', 12),
       ('Phường Bình Hưng Hoà B', 12),
       ('Phường Bình Trị Đông', 12),
       ('Phường Bình Trị Đông A', 12),
       ('Phường Bình Trị Đông B', 12),
       ('Phường Tân Tạo', 12),
       ('Phường Tân Tạo A', 12),
       ('Phường 01', 13),
       ('Phường 02', 13),
       ('Phường 03', 13),
       ('Phường 05', 13),
       ('Phường 06', 13),
       ('Phường 07', 13),
       ('Phường 11', 13),
       ('Phường 12', 13),
       ('Phường 13', 13),
       ('Phường 14', 13),
       ('Phường 15', 13),
       ('Phường 17', 13),
       ('Phường 19', 13),
       ('Phường 21', 13),
       ('Phường 22', 13),
       ('Phường 24', 13),
       ('Phường 25', 13),
       ('Phường 26', 13),
       ('Phường 27', 13),
       ('Phường 28', 13),
       ('Phường 01', 14),
       ('Phường 03', 14),
       ('Phường 04', 14),
       ('Phường 05', 14),
       ('Phường 06', 14),
       ('Phường 07', 14),
       ('Phường 08', 14),
       ('Phường 09', 14),
       ('Phường 10', 14),
       ('Phường 11', 14),
       ('Phường 12', 14),
       ('Phường 13', 14),
       ('Phường 14', 14),
       ('Phường 15', 14),
       ('Phường 16', 14),
       ('Phường 17', 14),
       ('Phường 01', 15),
       ('Phường 02', 15),
       ('Phường 03', 15),
       ('Phường 04', 15),
       ('Phường 05', 15),
       ('Phường 07', 15),
       ('Phường 08', 15),
       ('Phường 09', 15),
       ('Phường 10', 15),
       ('Phường 11', 15),
       ('Phường 13', 15),
       ('Phường 15', 15),
       ('Phường 17', 15),
       ('Phường 01', 16),
       ('Phường 02', 16),
       ('Phường 03', 16),
       ('Phường 04', 16),
       ('Phường 05', 16),
       ('Phường 06', 16),
       ('Phường 07', 16),
       ('Phường 08', 16),
       ('Phường 09', 16),
       ('Phường 10', 16),
       ('Phường 11', 16),
       ('Phường 12', 16),
       ('Phường 13', 16),
       ('Phường 14', 16),
       ('Phường 15', 16),
       ('Phường Hiệp Tân', 17),
       ('Phường Hoà Thạnh', 17),
       ('Phường Phú Thạnh', 17),
       ('Phường Phú Thọ Hoà', 17),
       ('Phường Phú Trung', 17),
       ('Phường Sơn Kỳ', 17),
       ('Phường Tân Qúy', 17),
       ('Phường Tân Sơn Nhì', 17),
       ('Phường Tân Thành', 17),
       ('Phường Tân Thới Hoà', 17),
       ('Phường Tây Thạnh', 17),
       ('Thị trấn Tân Túc', 18),
       ('Xã An Phú Tây', 18),
       ('Xã Bình Chánh', 18),
       ('Xã Bình Hưng', 18),
       ('Xã Bình Lợi', 18),
       ('Xã Đa Phước', 18),
       ('Xã Hưng Long', 18),
       ('Xã Lê Minh Xuân', 18),
       ('Xã Phạm Văn Hai', 18),
       ('Xã Phong Phú', 18),
       ('Xã Quy Đức', 18),
       ('Xã Tân Kiên', 18),
       ('Xã Tân Nhựt', 18),
       ('Xã Tân Quý Tây', 18),
       ('Xã Vĩnh Lộc A', 18),
       ('Xã Vĩnh Lộc B', 18),
       ('Thị trấn Cần Thạnh', 19),
       ('Xã An Thới Đông', 19),
       ('Xã Bình Khánh', 19),
       ('Xã Long Hòa', 19),
       ('Xã Lý Nhơn', 19),
       ('Xã Tam Thôn Hiệp', 19),
       ('Xã Thạnh An', 19),
       ('Thị trấn Củ Chi', 20),
       ('Xã An Nhơn Tây', 20),
       ('Xã An Phú', 20),
       ('Xã Bình Mỹ', 20),
       ('Xã Hòa Phú', 20),
       ('Xã Nhuận Đức', 20),
       ('Xã Phạm Văn Cội', 20),
       ('Xã Phú Hòa Đông', 20),
       ('Xã Phú Mỹ Hưng', 20),
       ('Xã Phước Hiệp', 20),
       ('Xã Phước Thạnh', 20),
       ('Xã Phước Vĩnh An', 20),
       ('Xã Tân An Hội', 20),
       ('Xã Tân Phú Trung', 20),
       ('Xã Tân Thạnh Đông', 20),
       ('Xã Tân Thạnh Tây', 20),
       ('Xã Tân Thông Hội', 20),
       ('Xã Thái Mỹ', 20),
       ('Xã Trung An', 20),
       ('Xã Trung Lập Hạ', 20),
       ('Xã Trung Lập Thượng', 20),
       ('Thị trấn Hóc Môn', 21),
       ('Xã Bà Điểm', 21),
       ('Xã Đông Thạnh', 21),
       ('Xã Nhị Bình', 21),
       ('Xã Tân Hiệp', 21),
       ('Xã Tân Thới Nhì', 21),
       ('Xã Tân Xuân', 21),
       ('Xã Thới Tam Thôn', 21),
       ('Xã Trung Chánh', 21),
       ('Xã Xuân Thới Đông', 21),
       ('Xã Xuân Thới Sơn', 21),
       ('Xã Xuân Thới Thượng', 21),
       ('Thị trấn Nhà Bè', 22),
       ('Xã Hiệp Phước', 22),
       ('Xã Long Thới', 22),
       ('Xã Nhơn Đức', 22),
       ('Xã Phú Xuân', 22),
       ('Xã Phước Kiển', 22),
       ('Xã Phước Lộc', 22);

INSERT INTO ward (name, district_id)
VALUES ('Phường Cống Vị', 23),
       ('Phường Điện Biên', 23),
       ('Phường Đội Cấn', 23),
       ('Phường Giảng Võ', 23),
       ('Phường Kim Mã', 23),
       ('Phường Liễu Giai', 23),
       ('Phường Ngọc Hà', 23),
       ('Phường Ngọc Khánh', 23),
       ('Phường Nguyễn Trung Trực', 23),
       ('Phường Phúc Xá', 23),
       ('Phường Quán Thánh', 23),
       ('Phường Thành Công', 23),
       ('Phường Trúc Bạch', 23),
       ('Phường Vĩnh Phúc', 23),
       ('Phường Dịch Vọng', 24),
       ('Phường Dịch Vọng Hậu', 24),
       ('Phường Mai Dịch', 24),
       ('Phường Nghĩa Đô', 24),
       ('Phường Nghĩa Tân', 24),
       ('Phường Quan Hoa', 24),
       ('Phường Trung Hòa', 24),
       ('Phường Yên Hòa', 24),
       ('Phường Phúc Tân', 25),
       ('Phường Đồng Xuân', 25),
       ('Phường Hàng Mã', 25),
       ('Phường Hàng Buồm', 25),
       ('Phường Hàng Đào', 25),
       ('Phường Hàng Bồ', 25),
       ('Phường Cửa Đông', 25),
       ('Phường Lý Thái Tổ', 25),
       ('Phường Hàng Bạc', 25),
       ('Phường Hàng Gai', 25),
       ('Phường Chương Dương', 25),
       ('Phường Hàng Trống', 25),
       ('Phường Cửa Nam', 25),
       ('Phường Hàng Bông', 25),
       ('Phường Tràng Tiền', 25),
       ('Phường Trần Hưng Đạo', 25),
       ('Phường Phan Chu Trinh', 25),
       ('Phường Hàng Bài', 25),
       ('Phường Nguyễn Du', 26),
       ('Phường Bạch Đằng', 26),
       ('Phường Phạm Đình Hổ', 26),
       ('Phường Lê Đại Hành', 26),
       ('Phường Đồng Nhân', 26),
       ('Phường Phố Huế', 26),
       ('Phường Đống Mác', 26),
       ('Phường Thanh Lương', 26),
       ('Phường Thanh Nhàn', 26),
       ('Phường Cầu Dền', 26),
       ('Phường Bách Khoa', 26),
       ('Phường Đồng Tâm', 26),
       ('Phường Vĩnh Tuy', 26),
       ('Phường Bạch Mai', 26),
       ('Phường Quỳnh Mai', 26),
       ('Phường Quỳnh Lôi', 26),
       ('Phường Minh Khai', 26),
       ('Phường Trương Định', 26),
       ('Phường Đại Kim', 27),
       ('Phường Định Công', 27),
       ('Phường Giáp Bát', 27),
       ('Phường Hoàng Liệt', 27),
       ('Phường Hoàng Văn Thụ', 27),
       ('Phường Lĩnh Nam', 27),
       ('Phường Mai Động', 27),
       ('Phường Tân Mai', 27),
       ('Phường Thanh Trì', 27),
       ('Phường Thịnh Liệt', 27),
       ('Phường Trần Phú', 27),
       ('Phường Tương Mai', 27),
       ('Phường Vĩnh Hưng', 27),
       ('Phường Yên Sở', 27),
       ('Phường Cát Linh', 28),
       ('Phường Hàng Bột', 28),
       ('Phường Khâm Thiên', 28),
       ('Phường Khương Thượng', 28),
       ('Phường Kim Liên', 28),
       ('Phường Láng Hạ', 28),
       ('Phường Láng Thượng', 28),
       ('Phường Nam Đồng', 28),
       ('Phường Ngã Tư Sở', 28),
       ('Phường Ô Chợ Dừa', 28),
       ('Phường Phương Liên', 28),
       ('Phường Phương Mai', 28),
       ('Phường Quang Trung', 28),
       ('Phường Quốc Tử Giám', 28),
       ('Phường Thịnh Quang', 28),
       ('Phường Thổ Quan', 28),
       ('Phường Trung Liệt', 28),
       ('Phường Trung Phụng', 28),
       ('Phường Trung Tự', 28),
       ('Phường Văn Chương', 28),
       ('Phường Văn Miếu', 28),
       ('Phường Bưởi', 29),
       ('Phường Nhật Tân', 29),
       ('Phường Phú Thượng', 29),
       ('Phường Quảng An', 29),
       ('Phường Thụy Khuê', 29),
       ('Phường Tứ Liên', 29),
       ('Phường Xuân La', 29),
       ('Phường Yên Phụ', 29),
       ('Phường Hạ Đình', 30),
       ('Phường Khương Đình', 30),
       ('Phường Khương Mai', 30),
       ('Phường Khương Trung', 30),
       ('Phường Kim Giang', 30),
       ('Phường Nhân Chính', 30),
       ('Phường Phương Liệt', 30),
       ('Phường Thanh Xuân Bắc', 30),
       ('Phường Thanh Xuân Nam', 30),
       ('Phường Thanh Xuân Trung', 30),
       ('Phường Thượng Đình', 30),
       ('Phường Thụy Phương', 31),
       ('Phường Xuân Tảo', 31),
       ('Phường Đức Thắng', 31),
       ('Phường Minh Khai', 31),
       ('Phường Cổ Nhuế 1', 31),
       ('Phường Cổ Nhuế 2', 31),
       ('Phường Tây Tựu', 31),
       ('Phường Liên Mạc', 31),
       ('Phường Xuân Đỉnh', 31),
       ('Phường Đông Ngạc', 31),
       ('Phường Phúc Diễn', 31),
       ('Phường Thượng Cát', 31),
       ('Phường Phú Diễn', 31),
       ('Phường La Khê', 32),
       ('Phường Mộ Lao', 32),
       ('Phường Biên Giang', 32),
       ('Phường Yên Nghĩa', 32),
       ('Phường Đồng Mai', 32),
       ('Phường Dương Nội', 32),
       ('Phường Vạn Phúc', 32),
       ('Phường Yết Kiêu', 32),
       ('Phường Phúc La', 32),
       ('Phường Hà Cầu', 32),
       ('Phường Phú La', 32),
       ('Phường Văn Quán', 32),
       ('Phường Phú Lương', 32),
       ('Phường Quang Trung', 32),
       ('Phường Phú Lãm', 32),
       ('Phường Kiến Hưng', 32),
       ('Phường Nguyễn Trãi', 32),
       ('Phường Thượng Thanh', 33),
       ('Phường Ngọc Thụy', 33),
       ('Phường Giang Biên', 33),
       ('Phường Đức Giang', 33),
       ('Phường Việt Hưng', 33),
       ('Phường Gia Thụy', 33),
       ('Phường Ngọc Lâm', 33),
       ('Phường Phúc Lợi', 33),
       ('Phường Bồ Đề', 33),
       ('Phường Sài Đồng', 33),
       ('Phường Long Biên', 33),
       ('Phường Thạch Bàn', 33),
       ('Phường Phúc Đồng', 33),
       ('Phường Cự Khối', 33),
       ('Phường Cầu Diễn', 34),
       ('Phường Mỹ Đình 1', 34),
       ('Phường Mỹ Đình 2', 34),
       ('Phường Phú Đô', 34),
       ('Phường Mễ Trì', 34),
       ('Phường Trung Văn', 34),
       ('Phường Đại Mỗ', 34),
       ('Phường Tây Mỗ', 34),
       ('Phường Phương Canh', 34),
       ('Phường Xuân Phương', 34),
       ('Thị trấn Tây Đằng', 35),
       ('Xã Ba Trại', 35),
       ('Xã Ba Vì', 35),
       ('Xã Cẩm Lĩnh', 35),
       ('Xã Cam Thượng', 35),
       ('Xã Châu Sơn', 35),
       ('Xã Chu Minh', 35),
       ('Xã Cổ Đô', 35),
       ('Xã Đông Quang', 35),
       ('Xã Đồng Thái', 35),
       ('Xã Khánh Thượng', 35),
       ('Xã Minh Châu', 35),
       ('Xã Minh Quang', 35),
       ('Xã Phong Vân', 35),
       ('Xã Phú Châu', 35),
       ('Xã Phú Cường', 35),
       ('Xã Phú Đông', 35),
       ('Xã Phú Phương', 35),
       ('Xã Phú Sơn', 35),
       ('Xã Sơn Đà', 35),
       ('Xã Tản Hồng', 35),
       ('Xã Tản Lĩnh', 35),
       ('Xã Thái Hòa', 35),
       ('Xã Thuần Mỹ', 35),
       ('Xã Thụy An', 35),
       ('Xã Tiên Phong', 35),
       ('Xã Tòng Bạt', 35),
       ('Xã Vân Hòa', 35),
       ('Xã Vạn Thắng', 35),
       ('Xã Vật Lại', 35),
       ('Xã Yên Bài', 35),
       ('Thị trấn Chúc Sơn', 36),
       ('Thị trấn Xuân Mai', 36),
       ('Xã Đại Yên', 36),
       ('Xã Đông Phương Yên', 36),
       ('Xã Đông Sơn', 36),
       ('Xã Đồng Lạc', 36),
       ('Xã Đồng Phú', 36),
       ('Xã Hòa Chính', 36),
       ('Xã Hoàng Diệu', 36),
       ('Xã Hoàng Văn Thụ', 36),
       ('Xã Hồng Phong', 36),
       ('Xã Hợp Đồng', 36),
       ('Xã Hữu Văn', 36),
       ('Xã Lam Điền', 36),
       ('Xã Mỹ Lương', 36),
       ('Xã Nam Phương Tiến', 36),
       ('Xã Ngọc Hòa', 36),
       ('Xã Phú Nam An', 36),
       ('Xã Phú Nghĩa', 36),
       ('Xã Phụng Châu', 36),
       ('Xã Quảng Bị', 36),
       ('Xã Tân Tiến', 36),
       ('Xã Tiên Phương', 36),
       ('Xã Tốt Động', 36),
       ('Xã Thanh Bình', 36),
       ('Xã Thủy Xuân Tiên', 36),
       ('Xã Thụy Hương', 36),
       ('Xã Thượng Vực', 36),
       ('Xã Trần Phú', 36),
       ('Xã Trung Hòa', 36),
       ('Xã Trường Yên', 36),
       ('Xã Văn Võ', 36),
       ('Thị trấn Phùng', 37),
       ('Xã Đan Phượng', 37),
       ('Xã Đồng Tháp', 37),
       ('Xã Hạ Mỗ', 37),
       ('Xã Hồng Hà', 37),
       ('Xã Liên Hà', 37),
       ('Xã Liên Hồng', 37),
       ('Xã Liên Trung', 37),
       ('Xã Phương Đình', 37),
       ('Xã Song Phượng', 37),
       ('Xã Tân Hội', 37),
       ('Xã Tân Lập', 37),
       ('Xã Thọ An', 37),
       ('Xã Thọ Xuân', 37),
       ('Xã Thượng Mỗ', 37),
       ('Xã Trung Châu', 37),
       ('Thị trấn Đông Anh', 38),
       ('Xã Bắc Hồng', 38),
       ('Xã Cổ Loa', 38),
       ('Xã Đại Mạch', 38),
       ('Xã Đông Hội', 38),
       ('Xã Dục Tú', 38),
       ('Xã Hải Bối', 38),
       ('Xã Kim Chung', 38),
       ('Xã Kim Nỗ', 38),
       ('Xã Liên Hà', 38),
       ('Xã Mai Lâm', 38),
       ('Xã Nam Hồng', 38),
       ('Xã Nguyên Khê', 38),
       ('Xã Tàm Xá', 38),
       ('Xã Thụy Lâm', 38),
       ('Xã Tiên Dương', 38),
       ('Xã Uy Nỗ', 38),
       ('Xã Vân Hà', 38),
       ('Xã Vân Nội', 38),
       ('Xã Việt Hùng', 38),
       ('Xã Vĩnh Ngọc', 38),
       ('Xã Võng La', 38),
       ('Xã Xuân Canh', 38),
       ('Xã Xuân Nộn', 38),
       ('Thị trấn Trâu Quỳ', 39),
       ('Thị trấn Yên Viên', 39),
       ('Xã Bát Tràng', 39),
       ('Xã Cổ Bi', 39),
       ('Xã Đa Tốn', 39),
       ('Xã Đặng Xá', 39),
       ('Xã Phú Thị', 39),
       ('Xã Đông Dư', 39),
       ('Xã Dương Hà', 39),
       ('Xã Dương Quang', 39),
       ('Xã Dương Xá', 39),
       ('Xã Kiêu Kỵ', 39),
       ('Xã Kim Lan', 39),
       ('Xã Văn Đức', 39),
       ('Xã Lệ Chi', 39),
       ('Xã Ninh Hiệp', 39),
       ('Xã Đình Xuyên', 39),
       ('Xã Phù Đổng', 39),
       ('Xã Trung Mầu', 39),
       ('Xã Yên Thường', 39),
       ('Xã Yên Viên', 39),
       ('Xã Kim Sơn', 39),
       ('Thị trấn Trạm Trôi', 40),
       ('Xã An Khánh', 40),
       ('Xã An Thượng', 40),
       ('Xã Cát Quế', 40),
       ('Xã Đắc Sở', 40),
       ('Xã Di Trạch', 40),
       ('Xã Đông La', 40),
       ('Xã Đức Giang', 40),
       ('Xã Đức Thượng', 40),
       ('Xã Dương Liễu', 40),
       ('Xã Kim Chung', 40),
       ('Xã La Phù', 40),
       ('Xã Lại Yên', 40),
       ('Xã Minh Khai', 40),
       ('Xã Sơn Đồng', 40),
       ('Xã Song Phương', 40),
       ('Xã Tiền Yên', 40),
       ('Xã Vân Canh', 40),
       ('Xã Vân Côn', 40),
       ('Xã Yên Sở', 40),
       ('Thị trấn Chi Đông', 41),
       ('Thị trấn Quang Minh', 41),
       ('Xã Chu Phan', 41),
       ('Xã Đại Thịnh (huyện lỵ)', 41),
       ('Xã Mê Linh', 41),
       ('Xã Hoàng Kim', 41),
       ('Xã Kim Hoa', 41),
       ('Xã Liên Mạc', 41),
       ('Xã Tam Đồng', 41),
       ('Xã Thạch Đà', 41),
       ('Xã Thanh Lâm', 41),
       ('Xã Tiền Phong', 41),
       ('Xã Tiến Thắng', 41),
       ('Xã Tiến Thịnh', 41),
       ('Xã Tráng Việt', 41),
       ('Xã Tự Lập', 41),
       ('Xã Văn Khê', 41),
       ('Xã Vạn Yên', 41),
       ('Thị trấn Đại Nghĩa', 42),
       ('Xã An Mỹ', 42),
       ('Xã An Phú', 42),
       ('Xã An Tiến', 42),
       ('Xã Bột Xuyên', 42),
       ('Xã Đại Hưng', 42),
       ('Xã Đốc Tín', 42),
       ('Xã Đồng Tâm', 42),
       ('Xã Hồng Sơn', 42),
       ('Xã Hợp Thanh', 42),
       ('Xã Hợp Tiến', 42),
       ('Xã Hùng Tiến', 42),
       ('Xã Hương Sơn', 42),
       ('Xã Lê Thanh', 42),
       ('Xã Mỹ Thành', 42),
       ('Xã Phù Lưu Tế', 42),
       ('Xã Phúc Lâm', 42),
       ('Xã Phùng Xá', 42),
       ('Xã Thượng Lâm', 42),
       ('Xã Tuy Lai', 42),
       ('Xã Vạn Kim', 42),
       ('Xã Xuy Xá', 42),
       ('Thị trấn Phú Xuyên', 43),
       ('Thị trấn Phú Minh', 43),
       ('Xã Bạch Hạ', 43),
       ('Xã Châu Can', 43),
       ('Xã Chuyên Mỹ', 43),
       ('Xã Đại Thắng', 43),
       ('Xã Đại Xuyên', 43),
       ('Xã Hoàng Long', 43),
       ('Xã Hồng Minh', 43),
       ('Xã Hồng Thái', 43),
       ('Xã Khai Thái', 43),
       ('Xã Minh Tân', 43),
       ('Xã Nam Phong', 43),
       ('Xã Nam Tiến', 43),
       ('Xã Nam Triều', 43),
       ('Xã Phú Túc', 43),
       ('Xã Phú Yên', 43),
       ('Xã Phúc Tiến', 43),
       ('Xã Phượng Dực', 43),
       ('Xã Quang Lãng', 43),
       ('Xã Quang Trung', 43),
       ('Xã Sơn Hà', 43),
       ('Xã Tân Dân', 43),
       ('Xã Tri Thủy', 43),
       ('Xã Tri Trung', 43),
       ('Xã Văn Hoàng', 43),
       ('Xã Vân Từ', 43),
       ('Thị trấn Phúc Thọ', 44),
       ('Xã Hát Môn', 44),
       ('Xã Hiệp Thuận', 44),
       ('Xã Liên Hiệp', 44),
       ('Xã Long Xuyên', 44),
       ('Xã Ngọc Tảo', 44),
       ('Xã Phúc Hòa', 44),
       ('Xã Phụng Thượng', 44),
       ('Xã Sen Phương', 44),
       ('Xã Tam Hiệp', 44),
       ('Xã Tam Thuấn', 44),
       ('Xã Thanh Đa', 44),
       ('Xã Thọ Lộc', 44),
       ('Xã Thượng Cốc', 44),
       ('Xã Tích Giang', 44),
       ('Xã Trạch Mỹ Lộc', 44),
       ('Xã Vân Hà', 44),
       ('Xã Vân Nam', 44),
       ('Xã Vân Phúc', 44),
       ('Xã Võng Xuyên', 44),
       ('Xã Xuân Đình', 44),
       ('Thị trấn Quốc Oai', 45),
       ('Xã Cấn Hữu', 45),
       ('Xã Cộng Hòa', 45),
       ('Xã Đại Thành', 45),
       ('Xã Đồng Quang', 45),
       ('Xã Đông Yên', 45),
       ('Xã Hòa Thạch', 45),
       ('Xã Liệp Tuyết', 45),
       ('Xã Nghĩa Hương', 45),
       ('Xã Ngọc Liệp', 45),
       ('Xã Ngọc Mỹ', 45),
       ('Xã Phú Cát', 45),
       ('Xã Phú Mãn', 45),
       ('Xã Phượng Cách', 45),
       ('Xã Sài Sơn', 45),
       ('Xã Tân Hòa', 45),
       ('Xã Tân Phú', 45),
       ('Xã Thạch Thán', 45),
       ('Xã Tuyết Nghĩa', 45),
       ('Xã Yên Sơn', 45),
       ('Xã Đông Xuân', 45),
       ('Thị trấn Sóc Sơn', 46),
       ('Xã Bắc Phú', 46),
       ('Xã Bắc Sơn', 46),
       ('Xã Đông Xuân', 46),
       ('Xã Đức Hòa', 46),
       ('Xã Hiền Ninh', 46),
       ('Xã Hồng Kỳ', 46),
       ('Xã Kim Lũ', 46),
       ('Xã Mai Đình', 46),
       ('Xã Minh Phú', 46),
       ('Xã Minh Trí', 46),
       ('Xã Nam Sơn', 46),
       ('Xã Phú Cường', 46),
       ('Xã Phù Linh', 46),
       ('Xã Phù Lỗ', 46),
       ('Xã Phú Minh', 46),
       ('Xã Quang Tiến', 46),
       ('Xã Tân Dân', 46),
       ('Xã Tân Hưng', 46),
       ('Xã Tân Minh', 46),
       ('Xã Thạnh Xuân', 46),
       ('Xã Tiên Dược', 46),
       ('Xã Trung Giã', 46),
       ('Xã Việt Long', 46),
       ('Xã Xuân Giang', 46),
       ('Xã Xuân Thu', 46),
       ('Thị trấn Liên Quan', 47),
       ('Xã Bình Phú', 47),
       ('Xã Bình Yên', 47),
       ('Xã Cẩm Yên', 47),
       ('Xã Cần Kiệm', 47),
       ('Xã Canh Nậu', 47),
       ('Xã Chàng Sơn', 47),
       ('Xã Đại Đồng', 47),
       ('Xã Dị Nậu', 47),
       ('Xã Đồng Trúc', 47),
       ('Xã Hạ Bằng', 47),
       ('Xã Hương Ngải', 47),
       ('Xã Hữu Bằng', 47),
       ('Xã Kim Quan', 47),
       ('Xã Lại Thượng', 47),
       ('Xã Phú Kim', 47),
       ('Xã Phùng Xá', 47),
       ('Xã Tân Xã', 47),
       ('Xã Thạch Hòa', 47),
       ('Xã Thạch Xá', 47),
       ('Xã Tiến Xuân', 47),
       ('Xã Yên Bình', 47),
       ('Xã Yên Trung', 47),
       ('Thị trấn Kim Bài', 48),
       ('Xã Bích Hòa', 48),
       ('Xã Bình Minh', 48),
       ('Xã Cao Dương', 48),
       ('Xã Cao Viên', 48),
       ('Xã Cự Khê', 48),
       ('Xã Dân Hòa', 48),
       ('Xã Đỗ Động', 48),
       ('Xã Hồng Dương', 48),
       ('Xã Kim An', 48),
       ('Xã Kim Thư', 48),
       ('Xã Liên Châu', 48),
       ('Xã Mỹ Hưng', 48),
       ('Xã Phương Trung', 48),
       ('Xã Tam Hưng', 48),
       ('Xã Tân Ước', 48),
       ('Xã Thanh Cao', 48),
       ('Xã Thanh Mai', 48),
       ('Xã Thanh Thùy', 48),
       ('Xã Thanh Văn', 48),
       ('Xã Xuân Dương', 48),
       ('Thị trấn Văn Điển', 49),
       ('Xã Đại Áng', 49),
       ('Xã Đông Mỹ', 49),
       ('Xã Duyên Hà', 49),
       ('Xã Hữu Hòa', 49),
       ('Xã Liên Ninh', 49),
       ('Xã Ngọc Hồi', 49),
       ('Xã Ngũ Hiệp', 49),
       ('Xã Tả Thanh Oai', 49),
       ('Xã Tam Hiệp', 49),
       ('Xã Tân Triều', 49),
       ('Xã Thanh Liệt', 49),
       ('Xã Tứ Hiệp', 49),
       ('Xã Vạn Phúc', 49),
       ('Xã Vĩnh Quỳnh', 49),
       ('Xã Yên Mỹ', 49),
       ('Thị trấn Thường Tín', 50),
       ('Xã Chương Dương', 50),
       ('Xã Dũng Tiến', 50),
       ('Xã Duyên Thái', 50),
       ('Xã Hà Hồi', 50),
       ('Xã Hiền Giang', 50),
       ('Xã Hòa Bình', 50),
       ('Xã Khánh Hà', 50),
       ('Xã Hồng Vân', 50),
       ('Xã Lê Lợi', 50),
       ('Xã Liên Phương', 50),
       ('Xã Minh Cường', 50),
       ('Xã Nghiêm Xuyên', 50),
       ('Xã Nguyễn Trãi', 50),
       ('Xã Nhị Khê', 50),
       ('Xã Ninh Sở', 50),
       ('Xã Quất Động', 50),
       ('Xã Tân Minh', 50),
       ('Xã Thắng Lợi', 50),
       ('Xã Thống Nhất', 50),
       ('Xã Thư Phú', 50),
       ('Xã Tiền Phong', 50),
       ('Xã Tô Hiệu', 50),
       ('Xã Tự Nhiên', 50),
       ('Xã Vạn Điểm', 50),
       ('Xã Văn Bình', 50),
       ('Xã Văn Phú', 50),
       ('Xã Văn Tự', 50),
       ('Xã Vân Tảo', 50),
       ('Thị trấn Vân Đình', 51),
       ('Xã Cao Thành', 51),
       ('Xã Đại Cường', 51),
       ('Xã Đại Hùng', 51),
       ('Xã Đội Bình', 51),
       ('Xã Đông Lỗ', 51),
       ('Xã Đồng Tiến', 51),
       ('Xã Đồng Tân', 51),
       ('Xã Hoa Sơn', 51),
       ('Xã Hòa Lâm', 51),
       ('Xã Hòa Nam', 51),
       ('Xã Hòa Phú', 51),
       ('Xã Hòa Xá', 51),
       ('Xã Hồng Quang', 51),
       ('Xã Kim Đường', 51),
       ('Xã Liên Bạt', 51),
       ('Xã Lưu Hoàng', 51),
       ('Xã Minh Đức', 51),
       ('Xã Phù Lưu', 51),
       ('Xã Phương Tú', 51),
       ('Xã Quảng Phú Cầu', 51),
       ('Xã Sơn Công', 51),
       ('Xã Tảo Dương Văn', 51),
       ('Xã Trầm Lộng', 51),
       ('Xã Trung Tú', 51),
       ('Xã Trường Thịnh', 51),
       ('Xã Vạn Thái', 51),
       ('Xã Viên An', 51),
       ('Xã Viên Nội', 51),
       ('Phường Lê Lợi', 52),
       ('Phường Ngô Quyền', 52),
       ('Phường Phú Thịnh', 52),
       ('Phường Quang Trung', 52),
       ('Phường Sơn Lộc', 52),
       ('Phường Trung Hưng', 52),
       ('Phường Trung Sơn Trầm', 52),
       ('Phường Viên Sơn', 52),
       ('Phường Xuân Khanh', 52),
       ('Xã Cổ Đông', 52),
       ('Xã Đường Lâm', 52),
       ('Xã Kim Sơn', 52),
       ('Xã Sơn Đông', 52),
       ('Xã Thanh Mỹ', 52),
       ('Xã Xuân Sơn', 52);