INSERT INTO admission_method (name, code)
VALUES ('Kết quả thi tốt nghiệp THPT', '100'),
       ('Kết quả học tập cấp THPT (học bạ)', '200'),
       ('Tuyển thẳng theo quy định của Quy chế tuyển sinh (Điều 8)', '301'),
       ('Kết hợp giữa tuyển thẳng theo Đề án và các phương thức khác', '302'),
       ('Tuyển thẳng theo Đề án của CSĐT', '303'),
       ('Thi đánh giá năng lực, đánh giá tư duy do CSĐT tự tổ chức để xét tuyển', '401'),
       ('Sử dụng kết quả thi đánh giá năng lực, đánh giá tư duy do đơn vị khác tổ chức để xét tuyển', '402'),
       ('Thi văn hóa do CSĐT tổ chức để xét tuyển', '403'),
       ('Sử dụng kết quả thi văn hóa do CSĐT khác tổ chức để xét tuyển', '404'),
       ('Kết hợp kết quả thi tốt nghiệp THPT với điểm thi năng khiếu để xét tuyển', '405'),
       ('Kết hợp kết quả học tập cấp THPT với điểm thi năng khiếu để xét tuyển', '406'),
       ('Kết hợp kết quả thi tốt nghiệp THPT với kết quả học tập cấp THPT để xét tuyển', '407'),
       ('Chỉ sử dụng chứng chỉ quốc tế để xét tuyển', '408'),
       ('Kết hợp kết quả thi tốt nghiệp THPT với chứng chỉ quốc tế để xét tuyển', '409'),
       ('Kết hợp kết quả học tập cấp THPT với chứng chỉ quốc tế để xét tuyển', '410'),
       ('Thí sinh tốt nghiệp THPT nước ngoài', '411'),
       ('Qua phỏng vấn', '412'),
       ('Kết hợp kết quả thi tốt nghiệp THPT với phỏng vấn để xét tuyển', '413'),
       ('Kết hợp kết quả học tập cấp THPT với phỏng vấn để xét tuyển', '414'),
       ('Sử dụng phương thức khác', '500');