INSERT INTO `institution` (`name`, `code`, `description`, `website_1`, `website_title_1`,
                           `website_2`, `website_title_2`, `website_3`, `website_title_3`, `email_1`, `email_title_1`,
                           `email_2`, `email_title_2`, `email_3`, `email_title_3`, `phone_1`, `phone_title_1`,
                           `phone_2`, `phone_title_2`, `phone_3`, `phone_title_3`, `avatar_link`)
VALUES ('Trường Đại học Bách Khoa TP.HCM - ĐHQG TP.HCM', 'QSB', 'Đại học Bách Khoa Thành phố Hồ Chí Minh (BKU) là một trong những cơ sở giáo dục hàng đầu tại Việt Nam, với hơn 60 năm phát triển và uy tín vững chắc. Trường nằm ở trung tâm thành phố, tạo điều kiện thuận lợi cho sinh viên tiếp cận với các nguồn lực và cơ hội nghề nghiệp.', 'https://hcmut.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'info@hcmut.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QSB.jpg?alt=media&token=1d430c43-706e-4889-85e8-8ca7e9132b88'),
       ('Trường Đại học Công nghệ Thông tin - ĐHQG TP.HCM', 'QSC', 'Trường Đại học Công nghệ Thông tin - Đại học Quốc gia Thành phố Hồ Chí Minh (UIT) là một trong những cơ sở giáo dục hàng đầu về công nghệ thông tin tại Việt Nam. Với mục tiêu đào tạo và nghiên cứu về các lĩnh vực công nghệ thông tin và truyền thông, UIT cam kết cung cấp một môi trường học tập và nghiên cứu chất lượng, thú vị và phù hợp với các tiêu chuẩn quốc tế.', 'https://www.uit.edu.vn/',
        'Trang chủ', NULL, NULL, NULL, NULL, 'info@uit.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL,
        '(028) 372 52002', 'Điện thoại chính', NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QSC.png?alt=media&token=9b8dff4a-89e3-4ca2-a356-3029e110c82c'),
       ('Trường Đại học Khoa học Tự nhiên - ĐHQG TP.HCM', 'QST', 'Trường Đại học Khoa học Tự nhiên - Đại học Quốc gia Thành phố Hồ Chí Minh (HCMUS) là một trong những cơ sở giáo dục hàng đầu về khoa học tự nhiên tại Việt Nam. Với hơn 70 năm phát triển và uy tín vững chắc, HCMUS cam kết cung cấp một môi trường học tập và nghiên cứu chất lượng, khuyến khích sự sáng tạo và khám phá khoa học.', 'https://hcmus.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'info@hcmus.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028) 62884499',
        'Điện thoại chính', NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QST.jpg?alt=media&token=c6b0b4e7-e21e-4ba7-9421-57b7c0e163d8'),
       ('Trường Đại học Khoa học Xã hội và Nhân văn TP.HCM - ĐHQG TP.HCM', 'QSX', 'Trường Đại học Khoa học Xã hội và Nhân văn TP.HCM (ĐHXH&NV) là một trong những cơ sở giáo dục hàng đầu về khoa học xã hội và nhân văn tại Việt Nam. Với hơn 60 năm thành lập và phát triển, ĐHXH&NV tự hào về việc cung cấp một môi trường học tập và nghiên cứu chất lượng, tạo điều kiện cho sinh viên khám phá sâu hơn về xã hội và con người.',
        'https://hcmussh.edu.vn/', 'Trang chủ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        '(028) 3823 5899', 'Điện thoại chính', NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QSX.jpg?alt=media&token=3370d121-85c4-4ff0-aa13-999e68852f3a'),
       ('Trường Đại học Kinh tế - Luật - ĐHQG TP.HCM', 'QSK',
        'Trường Đại học Kinh tế - Luật - Đại học Quốc gia Thành phố Hồ Chí Minh (UEL) là một trong những cơ sở giáo dục hàng đầu về kinh tế và luật tại Việt Nam. Với hơn 40 năm thành lập và phát triển, UEL đã khẳng định được uy tín và vị thế trong lĩnh vực đào tạo và nghiên cứu.', 'https://www.uel.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'tuvantuyensinh@uel.edu.vn', 'Tuyển sinh', 'phonghanhchinh@uel.edu.vn',
        'Thông tin chung', 'cntt@uel.edu.vn', 'Kỹ thuật', '(028) 3 7244 555', 'Điện thoại chính', '(028) 37244 500',
        'Fax', '(028) 37244 550', 'Hỗ trợ tuyển sinh',
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QSK.png?alt=media&token=3b645e9e-cf5a-4464-8b74-e80891cd54da'),
       ('Trường Đại học Quốc Tế - ĐHQG TP.HCM', 'QSQ', 'Trường Đại học Quốc Tế - Đại học Quốc gia Thành phố Hồ Chí Minh (IU) là một trong những cơ sở giáo dục hàng đầu về quốc tế tại Việt Nam. Với cam kết cung cấp một môi trường học tập và nghiên cứu quốc tế, IU đồng thời tạo điều kiện cho sinh viên trải nghiệm văn hóa đa dạng và học tập trong một cộng đồng quốc tế.', 'https://hcmiu.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'info@hcmiu.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028) 37244270', 'Điện thoại chính',
        '(028) 37244271', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QSQ.png?alt=media&token=704c7ab7-928d-4a94-bd8d-4602d1dcbe54'),
       ('Trường Đại học Ngoại thương Cơ sở II TP. HCM', 'NTH', 'Trường Đại học Ngoại thương (ĐHNT) - Cơ sở II TP. Hồ Chí Minh là một trong những trường đại học hàng đầu về lĩnh vực kinh doanh và quản trị tại Việt Nam. Với hơn 60 năm thành lập và phát triển, ĐHNT đã xây dựng được uy tín vững chắc trong cả đào tạo và nghiên cứu.', 'https://cs2.ftu.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'qldt.cs2@ftu.edu.vn', 'Quản lý đào tạo', NULL, NULL, NULL, NULL, '(028)35127254',
        'Điện thoại chính', '(028)35127255', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NTH.png?alt=media&token=f8f242db-0b6d-46dc-a860-0277b4f3ee6d'),
       ('Trường Đại học Y Dược TP.HCM', 'YDS', 'Trường Đại học Y Dược TP.HCM là một trong những trường đào tạo y khoa hàng đầu tại Việt Nam. Trường được thành lập với mục tiêu cung cấp một nền tảng giáo dục chất lượng và đa chiều trong lĩnh vực y học.', 'https://ump.edu.vn/', 'Trang chủ', NULL, NULL, NULL,
        NULL, 'hanhchinh@ump.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(+84-28) 3855 8411', NULL,
        '(+84-28) 3853 7949', NULL, '(+84-28) 3855 5780', NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/YDS.jpg?alt=media&token=7e0fec20-676f-4c2a-9f91-77d785f6fa3b'),
       ('Trường Đại học Kinh tế TP.HCM', 'KSA', 'Trường Đại học Kinh tế TP.HCM (UEH) là một trong những cơ sở giáo dục hàng đầu về kinh tế tại Việt Nam. Với hơn 40 năm thành lập và phát triển, UEH đã khẳng định được uy tín và vị thế trong lĩnh vực đào tạo và nghiên cứu kinh tế.', 'https://www.ueh.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'info@ueh.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '84.28.38295299', 'Điện thoại chính',
        '84.28.38250359', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/KSA.jpg?alt=media&token=92a3a051-ccee-4d64-8f0e-ccc59208cca9'),
       ('Trường Đại học Sư phạm - Kỹ thuật TP.HCM', 'SPK', 'HCMUTE được thành lập với mục tiêu đào tạo và nghiên cứu các ngành liên quan đến giáo dục và kỹ thuật, nhằm đáp ứng nhu cầu ngày càng cao của xã hội về nhân lực chất lượng trong lĩnh vực này.', 'https://hcmute.edu.vn/', 'Trang chủ', NULL,
        NULL, NULL, NULL, 'ptchc@hcmute.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(+84 - 028) 38968641', NULL,
        '(+84 - 028) 38961333', NULL, '(+84 -028)37221223', NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/SPK.png?alt=media&token=841cd4e7-a942-4dbd-bd02-783764f996f1'),
       ('Trường Đại học Công Thương TP.HCM', 'DCT', 'Trường Đại học Công Thương TP.HCM được thành lập với sứ mệnh đào tạo và nghiên cứu về lĩnh vực kinh doanh, quản trị, và công nghệ. Trường đã có hơn 60 năm phát triển và khẳng định vị thế của mình trong cộng đồng giáo dục và doanh nghiệp.', 'https://huit.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'infor@hufi.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028)38161673', 'Điện thoại chính',
        NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DCT.jpeg?alt=media&token=69ccc00e-53f1-4a01-ba14-03a0c52d6b52'),
       ('Trường Đại học Công nghiệp TP.HCM', 'IUH', 'Trường Đại học Công nghiệp TP.HCM đã có hơn 40 năm hoạt động trong lĩnh vực đào tạo và nghiên cứu về công nghệ và quản lý sản xuất.', 'https://iuh.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'dhcn@iuh.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '2838940390', 'Điện thoại chính',
        '2839940954', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/IUH.jpg?alt=media&token=07ebe6a6-e65b-4efe-a219-1a284424fad0'),
       ('Trường Đại học Cảnh sát Nhân dân', 'CSS', 'Trường Đại học Cảnh sát Nhân dân có trụ sở chính tại Hà Nội và một số cơ sở đào tạo tại các tỉnh thành khác trên cả nước. Trường được thành lập để đào tạo và bồi dưỡng cán bộ, chiến sĩ Cảnh sát Nhân dân với mục tiêu chính là bảo vệ an ninh, trật tự và an toàn xã hội.', 'https://dhcsnd.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'contact@dhcsnd.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028)66860550', 'Trụ sở chính',
        '(028)38962767', 'Địa điểm đào tạo số 2', '02923.65.66.67', 'Địa điểm đào tạo số 3',
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/CSS.png?alt=media&token=4a21c409-960e-49b3-ba12-fe7f1c00951c'),
       ('Trường Đại học Giao thông Vận tải Phân hiệu tại TP.HCM', 'GSA', 'Trường Đại học Giao thông Vận tải - Phân hiệu tại TP.HCM là một phần của hệ thống UTC, trường đã có hơn 60 năm kinh nghiệm trong đào tạo và nghiên cứu về lĩnh vực giao thông vận tải.', 'https://utc2.edu.vn/',
        'Trang chủ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '(028).3896.2018', 'Đào tạo',
        '(028).3896.2819', 'Tuyển sinh', '(028).3736.054', 'Công tác chính trị sinh viên',
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/GSA.png?alt=media&token=453f6c67-8bc2-4dcf-8aa9-47d031edaef5'),
       ('Trường Đại học Giao thông Vận tải TP.HCM', 'UTH', 'Trường Đại học Giao thông Vận tải TP.HCM được thành lập với mục tiêu đào tạo và nghiên cứu các ngành liên quan đến giao thông, vận tải, kỹ thuật ô tô, kỹ thuật đường bộ, đường sắt và hàng không.', 'https://ut.edu.vn/', 'Trang chủ', NULL,
        NULL, NULL, NULL, 'ut-hcmc@ut.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '2835126902', 'Tuyển sinh',
        '2838992862', 'Phòng đào tạo', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/UTH.png?alt=media&token=2c5f39ba-1f32-40f3-8a26-b9be830fb10d'),
       ('Trường Đại học Sư phạm TP.HCM', 'SPS', 'Trường Đại học Sư phạm TP.HCM (HCMUTE) được thành lập với sứ mệnh đào tạo và nghiên cứu về giáo dục, giảng dạy và nghiên cứu khoa học.', 'https://hcmue.edu.vn/vi/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'portalsupport@hcmue.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(+84) - (28) - 38352020',
        'Điện thoại chính', '(+84) - (28) - 38398946', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/SPS.jpg?alt=media&token=bc5366fb-3470-4198-aee2-1c4a85d28eb5'),
       ('Trường Đại học Ngân hàng TP.HCM', 'NHS', 'Trường Đại học Ngân hàng TP.HCM (BUH) là một trong những cơ sở giáo dục hàng đầu về lĩnh vực ngân hàng, tài chính tại Việt Nam. Với sứ mệnh đào tạo và nghiên cứu về ngân hàng, tài chính và các lĩnh vực liên quan, BUH cam kết cung cấp một môi trường học tập và nghiên cứu chất lượng, thú vị và phù hợp với các tiêu chuẩn quốc tế.', 'https://hub.edu.vn/', 'Trang chủ', NULL, NULL, NULL,
        NULL, 'dhnhtphcm@hub.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028) 38 291901', 'Điện thoại chính',
        '(028)38 212584', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NHS.png?alt=media&token=b2e47a06-5232-4177-9d0c-2d54461a9411'),
       ('Trường Đại học Kiến Trúc TP.HCM', 'KTS', 'Trường Đại học Kiến trúc Thành phố Hồ Chí Minh (HCMUA) là một trong những cơ sở giáo dục hàng đầu về kiến trúc tại Việt Nam. Với hơn một thế kỷ lịch sử và phát triển, HCMUA đã khẳng định được uy tín và sứ mệnh của mình trong việc đào tạo và nghiên cứu về kiến trúc.', 'http://www.uah.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'phongqldt@uah.edu.vn', 'Phòng Quản lý Đào tạo', 'phongcthssv@uah.edu.vn',
        'Phòng Công tác sinh viên', NULL, NULL, '(028) 38.222748', 'Cơ sở chính', '(028) 37 228 277', 'Cơ sở Thủ Đức',
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/KTS.png?alt=media&token=43119dcf-cf65-4484-8d50-64c96dc1f95c'),
       ('Trường Đại học Lao động - Xã hội Cơ sở II', 'DLS', 'Trường Đại học Lao động - Xã hội là cơ sở giáo dục đại học công lập duy nhất của ngành LĐTBXH trong đào tạo nguồn nhân lực trình độ cao theo định hướng ứng dụng với thế mạnh là các ngành Quản trị nhân lực, Công tác xã hội, Bảo hiểm, Kế toán và Quản trị kinh doanh; là trung tâm nghiên cứu khoa học, chuyển giao công nghệ, hợp tác quốc tế trong lĩnh vực kinh tế - lao động – xã hội đáp ứng yêu cầu phát triển của Ngành, đất nước và hội nhập quốc tế.', 'http://ldxh.edu.vn/', 'Trang chủ', NULL,
        NULL, NULL, NULL, 'websiteldxh@gmail.com', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028) 3883 7218',
        'Điện thoại chính', '(028)3883 7218', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DLS.png?alt=media&token=759e4001-ae18-4c0f-bbea-002620817b81'),
       ('Trường Đại học Mở TP.HCM', 'MBS', 'Trường Đại học Mở TP.HCM (MOU) là một trong những cơ sở giáo dục hàng đầu về hình thức đào tạo mở và từ xa tại Việt Nam. MOU được biết đến với việc cung cấp các chương trình đào tạo linh hoạt và phong phú, phù hợp với nhu cầu và điều kiện của sinh viên.', 'https://ou.edu.vn/', 'Trang chủ', NULL, NULL, NULL, NULL,
        'ou@ou.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '028-38364748', 'Điện thoại chính', '028-39207639',
        'Fax 1', '028-39207640', 'Fax 2',
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/MBS.jpg?alt=media&token=b07261e7-e790-4c1b-8e4e-8c6fa42c915d'),
       ('Trường Đại học Mỹ thuật TP.HCM', 'MTS', 'Trường Đại học Mỹ thuật Thành phố Hồ Chí Minh (HCMC University of Fine Arts) là một trong những cơ sở giáo dục hàng đầu về nghệ thuật và thiết kế tại Việt Nam. Với hơn 50 năm phát triển, trường đã khẳng định được vị thế của mình trong lĩnh vực này.', 'https://hcmufa.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'daotao@hcmufa.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028) 38 416 010',
        'Phòng Đào tạo QLKH&HTQT', '(028) 35 100 328', 'Phòng Công tác Sinh viên', '(028) 38 030 237',
        'Phòng Hành chính Tổng hợp',
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/MTS.jpg?alt=media&token=b8d99d28-8800-4297-a693-4c211fdcce5f'),
       ('Phân viện Học viện Hành chính Quốc gia tại TP.HCM', 'DNV', 'Phân viện Học viện Hành chính Quốc gia tại TP.HCM (NAEM) là một trong những cơ sở giáo dục hàng đầu về hành chính công và quản lý công ở Việt Nam. Với sứ mệnh đào tạo và nghiên cứu về lĩnh vực này, NAEM cam kết cung cấp một môi trường học tập và nghiên cứu chất lượng, thú vị và phù hợp với các tiêu chuẩn chuyên ngành.', 'https://truongnoivu-csmn.edu.vn/',
        'Trang chủ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '028.3865.6054', 'Điện thoại chính',
        NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DNV.png?alt=media&token=d576969b-544f-4dda-9759-6cc3ae31ff9f'),
       ('Trường Đại học Sân khấu - Điện ảnh TP.HCM', 'DSD', 'Trường Đại học Sân khấu - Điện ảnh TP.HCM (HCMC University of Theater and Cinematography) là một trong những cơ sở giáo dục hàng đầu về nghệ thuật sân khấu và điện ảnh tại Việt Nam. Trường cung cấp các chương trình đào tạo đa dạng trong lĩnh vực sân khấu, điện ảnh, truyền thông và nghệ thuật biểu diễn.', 'https://skdahcm.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'info@example.com', 'Thư chính', NULL, NULL, NULL, NULL, '(028)38.393.658',
        'Phòng Đào tạo', '(028).38.364.900', 'Phòng Hành chính', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DSD.png?alt=media&token=70ca6164-a269-4fc8-89b6-57e19422e6e0'),
       ('Trường Đại học Sư phạm Thể dục Thể thao TP.HCM', 'STS', 'Trường Đại học Sư phạm Thể dục Thể thao TP.HCM (HCMC University of Physical Education and Sports) là một trong những cơ sở giáo dục hàng đầu về thể dục thể thao tại Việt Nam. Trường này chuyên đào tạo các chuyên viên, giáo viên và nhà nghiên cứu trong lĩnh vực thể dục thể thao và giáo dục thể chất.', 'https://upes.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'upes.hcmc@upes.edu.vn', 'Thư chính', 'bants.sts@moet.edu.vn', 'Tuyển sinh', NULL, NULL,
        '0283.85563', NULL, '0283.8555432', NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/STS.png?alt=media&token=9d760d34-c67b-4882-9616-782b7b77ed04'),
       ('Trường Đại học Thể dục Thể thao TP.HCM', 'TDS', 'Trường Đại học Thể dục Thể thao Thành phố Hồ Chí Minh là một trường đại học với mô hình kết hợp giữa đào tạo và huấn luyện, Trường Đại học TDTT TP.HCM đã luôn gắn chặt, kết nối các nhiệm vụ với nhau để hoàn thành tốt các chỉ tiêu về đào tạo cán bộ có trình độ đại học, thạc sĩ, tiến sĩ; tổ chức triển khai nhiều đề tài nghiên cứu khoa học mang tính thức tiễn, ứng dụng trực tiếp cho công tác giảng dạy, huấn luyện.', 'https://ush.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'info@ush.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '0283.896.0322', 'Điện thoại',
        '0282.248.2828', 'Hotline', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TDS.jpg?alt=media&token=0f4b32fb-29b8-40b6-95be-e3dba3ad9546'),
       ('Phân viện Trường Đại học Thủy lợi TP.HCM', 'TLS', 'Trường Đại học Thuỷ lợi là trường đại học công lập có sứ mệnh đào tạo nguồn nhân lực chất lượng cao, nghiên cứu khoa học, phát triển và chuyển giao công nghệ tiên tiến trong các ngành khoa học, kỹ thuật, kinh tế và quản lý, đặc biệt trong lĩnh vực thuỷ lợi, môi trường, phòng chống và giảm nhẹ thiên tai; góp phần thúc đẩy nhanh quá trình công nghiệp hoá, hiện đại hoá và phát triển bền vững Tổ quốc Việt Nam.', 'https://tlus.edu.vn/', 'Trang chủ', NULL,
        NULL, NULL, NULL, 'phanhieu@tlu.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(84).28.38400532',
        'Điện thoại chính', '(84).28.38400542', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TLS.png?alt=media&token=39075130-8f0d-44c9-9b59-99cc3ee086a0'),
       ('Trường Đại học Trần Đại Nghĩa', 'VPH', 'Trường Đại học Trần Đại Nghĩa là một cơ sở giáo dục tại Thành phố Hồ Chí Minh, Việt Nam. Trường này thường chuyên đào tạo trong các ngành nghề công nghệ thông tin, kinh doanh, quản lý, và các lĩnh vực khác.', 'http://tdnu.edu.vn/', 'Trang chủ', NULL, NULL, NULL,
        NULL, 'lienhe@tdnu.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '84.8.38940535', 'Điện thoại chính', NULL,
        NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/VPH.jpg?alt=media&token=51a6fd1f-b998-4843-abec-8e36cc5d00c7'),
       ('Trường Đại học Tài chính - Marketing', 'DMS', 'Trường Đại học Tài chính - Marketing (University of Finance - Marketing) là một trường đại học công lập chuyên ngành về nhóm ngành tài chính và quản lý tại miền Nam Việt Nam, với thế mạnh thương hiệu về đào tạo nhóm ngành tài chính và marketing.', 'https://ufm.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'tuyensinh@ufm.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '028 38726789', 'Điện thoại chính',
        '028 37720406', 'Tư vấn tuyển sinh 1', '028 37720407', 'Tư vấn tuyển sinh 2',
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DMS.png?alt=media&token=e265ab73-16b6-452c-bd88-8f5fcbcc8182'),
       ('Trường Đại học Tài nguyên - Môi trường TP.HCM', 'DTM', 'Trường Đại học Tài nguyên - Môi trường TP.HCM là một trong những cơ sở giáo dục hàng đầu về lĩnh vực tài nguyên và môi trường tại Thành phố Hồ Chí Minh. Trường chuyên đào tạo và nghiên cứu về các ngành liên quan đến tài nguyên tự nhiên, môi trường, quản lý và bảo vệ môi trường.', 'https://hcmunre.edu.vn/', 'Trang chủ',
        NULL, NULL, NULL, NULL, 'info@hcmunre.com', 'Thư điện tử', NULL, NULL, NULL, NULL, '028.38443006',
        'Điện thoại chính', NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DTM.png?alt=media&token=6228b314-7ca0-43b1-b2f3-7db5138c76a5'),
       ('Trường Đại học Tôn Đức Thắng', 'DTT', 'Trường Đại học Tôn Đức Thắng (TDTU) là một trong những trường đại học hàng đầu tại Thành phố Hồ Chí Minh, Việt Nam. Trường được đặt tên theo danh nhân Tôn Đức Thắng - Chủ tịch thứ hai của nước Cộng hòa Xã hội Chủ nghĩa Việt Nam.', 'https://tdtu.edu.vn/', 'Trang chủ', NULL, NULL, NULL,
        NULL, 'tonducthanguniversity@tdtu.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028) 37 755 035',
        'Điện thoại chính', '(028) 37 755 055', 'Fax', NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DTT.png?alt=media&token=4a6929f1-52b5-4f3b-bf08-4ab38ed95e70'),
       ('Trường Đại học Văn hóa TP.HCM', 'VHS', 'Trường Đại học Văn hóa TP.HCM (HUC) là một cơ sở giáo dục nổi tiếng tại Thành phố Hồ Chí Minh, Việt Nam. Trường chuyên đào tạo và nghiên cứu trong lĩnh vực văn hóa, nghệ thuật, và các ngành liên quan.', 'https://www.hcmuc.edu.vn/', 'Trang chủ', NULL, NULL,
        NULL, NULL, 'dhvh@hcmuc.edu.vn', 'Thư điện tử', NULL, NULL, NULL, NULL, '(028)38992901', 'Điện thoại chính',
        NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/VHS.png?alt=media&token=f3112668-60e5-4b09-a762-47068312098b'),
       ('Trường Đại học Luật - ĐHQG Hà Nội', 'QHL', 'Trường Đại học Luật - ĐHQG Hà Nội (HLU) là một trong những trường đại học nổi tiếng về lĩnh vực luật tại Việt Nam, và là thành viên của Đại học Quốc gia Hà Nội. Trường này có vai trò quan trọng trong việc đào tạo và nghiên cứu trong lĩnh vực pháp luật, cũng như đóng góp vào sự phát triển của hệ thống pháp luật và hệ thống tư pháp của đất nước.', 'https://law.vnu.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'lawsch@vnu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(04) 37547787', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHL.jpg?alt=media&token=fabcf31e-c083-4f53-93a8-a6afb5bb54e4'),
       ('Trường Quốc tế - ĐHQG Hà Nội', 'QHQ', 'Trường Quốc tế cung cấp nhiều chương trình đào tạo đa ngành, bao gồm các ngành khoa học tự nhiên, xã hội, kinh doanh, kỹ thuật, y tế, và nhiều lĩnh vực khác. Trường có môi trường học tập hiện đại, với các cơ sở vật chất và năng lực giảng dạy hàng đầu.', 'https://www.is.vnu.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'truongquocte@vnuis.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.3557.5992', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHQ.png?alt=media&token=c7985e21-6131-4037-a528-b5145cad4827'),
       ('Trường Đại học Công nghệ - ĐHQG Hà Nội', 'QHI', 'Trường Đại học Công nghệ (ĐHCN) được thành lập ngày 25/5/2004 trên cơ sở phát triển Khoa Công nghệ &Trung tâm Hợp tác Đào tạo và Bồi dưỡng Cơ học thuộc Đại học Quốc gia Hà Nội (ĐHQGHN). Trải qua chặng đường gần 20 năm xây dựng và phát triển, nhà trường đã khẳng định vị thế là một trong những ngôi trường đại học đào tạo, nghiên cứu về công nghệ, kỹ thuật hàng đầu cả nước và đang từng bước tiếp cận chuẩn mực quốc tế.', 'https://uet.vnu.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'uet@vnu.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.37547.461', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHI.png?alt=media&token=293fe73c-584a-4f15-aff6-170e48795f6e'),
       ('Trường ĐH Giáo dục - ĐHQG Hà Nội', 'QHS', 'Trường Đại học Giáo dục, ĐHQGHN là cơ sở giáo dục đại học đào tạo và nghiên cứu chất lượng cao và trình độ cao trong khoa học và công nghệ giáo dục, ứng dụng cho đào tạo giáo viên, cán bộ quản lý và các nhóm nhân lực khác trong lĩnh vực giáo dục.', 'http://education.vnu.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'education@vnu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 7301 7123', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHS.png?alt=media&token=ffbd71cb-9414-4946-a5c3-aed49e57d026'),
       ('Trường ĐH Khoa học Tự nhiên - ĐHQG Hà Nội', 'QHT', 'Trường ĐHKHTN là trường đại học nghiên cứu, có sứ mạng đào tạo nguồn nhân lực chất lượng cao, bồi dưỡng nhân tài, nghiên cứu sáng tạo và chuyển giao tri thức thuộc lĩnh vực khoa học và công nghệ, góp phần xây dựng, phát triển và bảo vệ đất nước.', 'http://www.hus.vnu.edu.vn/', NULL, NULL,
        NULL, NULL, NULL, 'hus@vnu.edu.vn', NULL, 'admin@hus.edu.vn', NULL, NULL, NULL, '(84) 0243-8584615', NULL,
        '(84) 0243-8581419', NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHT.png?alt=media&token=343087a5-7f2e-46b8-a890-b6e28266b5e9'),
       ('Trường ĐH Khoa học Xã hội và Nhân văn - ĐHQG Hà Nội', 'QHX', 'Trường ĐHKHXH&NV, ĐHQGHN có sứ mệnh đi đầu trong đào tạo nguồn nhân lực chất lượng cao, trình độ cao; nghiên cứu, sáng tạo và truyền bá tri thức về Khoa học xã hội và nhân văn, phục vụ sự nghiệp xây dựng, bảo vệ Tổ quốc và hội nhập quốc tế.', 'http://www.ussh.vnu.edu.vn/',
        NULL, NULL, NULL, NULL, NULL, 'contact@ussh.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 38 583 799', NULL, NULL,
        NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHX.jpg?alt=media&token=638a8e9e-79f8-4651-bb01-23e7a961a263'),
       ('Trường Đại học Kinh tế - ĐHQG Hà Nội', 'QHE', 'Cung cấp cho xã hội nguồn nhân lực chất lượng cao theo định hướng chuyên gia, lãnh đạo trong các lĩnh vực kinh tế, quản lý và quản trị kinh doanh đáp ứng nhu cầu phát triển chất lượng, hiệu quả và bền vững của Việt Nam; nghiên cứu và chuyển giao các kết quả nghiên cứu cho Chính phủ, các tổ chức, doanh nghiệp và xã hội; tạo môi trường thuận lợi để sáng tạo, nuôi dưỡng, phát triển tài năng trong các lĩnh vực kinh tế, quản lý và quản trị kinh doanh hiện đại.', 'https://ueb.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'news_ueb@vnu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84.24) 37547506', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHE.png?alt=media&token=d50dc42e-8084-444a-bfda-0c9993a81e59'),
       ('Trường Đại học Ngoại ngữ - ĐHQG Hà Nội', 'QHF', 'Trường Đại học Ngoại ngữ, là một trường đại học thành viên của Đại học Quốc gia Hà Nội, được xếp vào nhóm trường đại học trọng điểm quốc gia Việt Nam. Đây được đánh giá là trường đại học đầu ngành và có lịch sử lâu đời nhất về đào tạo và giảng dạy ngôn ngữ tại Việt Nam.', 'http://ulis.vnu.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'dhnn@vnu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84-4) 37547269', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHF.jpg?alt=media&token=0e9e1701-ba8a-44d7-83d5-97f17163fc2b'),
       ('Trường Đại học Việt Nhật - ĐHQG Hà Nội', 'QHJ', 'Trường Đại học Việt Nhật là một đơn vị thành viên của Đại học Quốc Gia Hà Nội, hệ thống Đảm bảo chất lượng giáo dục (ĐBCLGD) bên trong của Trường được xây dựng và phát triển nhằm hướng đến sự đánh giá, kiểm soát, duy trì và cải thiện liên tục chất lượng của mọi hoạt động trong Trường bao gồm cả hoạt động đào tạo, nghiên cứu và phục vụ cộng đồng, hướng đến tầm nhìn, sứ mạng, triết lý giáo dục của Trường và nhu cầu của các bên liên quan', 'https://vju.ac.vn/', NULL, NULL, NULL, NULL,
        NULL, 'admission@vju.ac.vn', NULL, 'info@vju.ac.vn', NULL, NULL, NULL, '(+84) 24 7306 6001', NULL, NULL, NULL,
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHJ.png?alt=media&token=d42b52d9-bf2e-4165-b8e2-67e5db76f5e0'),
       ('Trường Đại học Y Dược - ĐHQG Hà Nội', 'QHY', 'Với sứ mệnh đào tạo nguồn nhân lực y tế chất lượng cao, bồi dưỡng nhân tài dựa vào nghiên cứu, trên nền tảng khoa học cơ bản vững chắc, công nghệ cao và kinh tế - xã hội mũi nhọn, đóng góp tích cực trong đổi mới hệ thống giáo dục đại học Y, Dược ở Việt Nam. Trường Đại Học Y Dược xác định mục tiêu phát triển thành trường đại học định hướng nghiên cứu, thuộc nhóm đại học tiên tiến trong khu vực, đóng góp vào sự nghiệp chăm sóc sức khỏe nhân dân, phát triển nền khoa học sức khỏe của đất nước cũng như góp phần hoàn thiện mô hình đại học đa ngành, đa lĩnh vực, dựa trên nền tảng khoa học cơ bản và công nghệ cao, hội nhập nhanh và toàn diện vào mái nhà chung của ĐHQGHN.', 'http://ump.vnu.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'ump@vnu.edu.vn', NULL, NULL, NULL, NULL, NULL, '+84-24-3745.0188', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/QHY.jpg?alt=media&token=34380db8-0173-43e2-a69c-86977bca3cdd'),
       ('ĐẠI HỌC BÁCH KHOA HÀ NỘI', 'BKA', 'Đại học Bách khoa Hà Nội là đại học theo lĩnh vực kỹ thuật và công nghệ có trụ sở tại Hà Nội, Việt Nam. Đại học Bách khoa Hà Nội được xem là một trong những đại học kỹ thuật lớn nhất Việt Nam, trực thuộc Bộ Giáo dục và Đào tạo và được xếp vào nhóm các trường Đại học, Học viện trọng điểm của Quốc gia Việt Nam.', 'https://www.hust.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'vp@hust.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 3869 4242', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/BKA.jpg?alt=media&token=e3a739e4-35eb-42b0-9993-e08f163264de'),
       ('Học viện Âm nhạc Quốc gia Việt Nam', 'NVH', 'Học viện Âm nhạc Quốc gia Việt Nam được thành lập từ năm 1956, với ba chức năng chính là Đào tạo, Nghiên cứu khoa học và Biểu diễn âm nhạc. Học viện là một trong những trung tâm âm nhạc lớn, có uy tín của Việt Nam và khu vực.', 'http://www.vnam.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'hvan@vnam.edu.vn', NULL, NULL, NULL, NULL, NULL, '+844 3851 4969', NULL, '+844 3856 1842', NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NVH.png?alt=media&token=1227e7e0-43ec-4736-b8b7-5a939de1d0a3'),
       ('Học viện Báo chí Tuyên truyền', 'TGC', ' Học viện là trường Đảng, đồng thời là cơ sở giáo dục đại học trọng điểm, hàng đầu của Việt Nam. Tiếp tục khẳng định, giữ vững vị thế của một trường đại học hàng đầu trong đào tạo, bồi dưỡng, nghiên cứu lĩnh vực lý luận chính trị, công tác xây dựng Đảng và chính quyền Nhà nước, tư tưởng - văn hóa, báo chí và truyền thông với đội ngũ chuyên gia đầu ngành có tầm ảnh hưởng trong nước và quốc tế.', 'https://ajc.hcma.vn', NULL, NULL, NULL, NULL, NULL,
        'website@ajc.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 3754 6963', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TGC.jpg?alt=media&token=1d53272f-1918-4093-8100-78d351fe7408'),
       ('Học viện Chính sách và Phát triển', 'HCP', 'Đào tạo nguồn nhân lực chất lượng cao, trình độ cao về lĩnh vực kinh tế, kinh doanh, quản lý, quản trị, luật và chính sách phát triển, có tư duy năng động, sáng tạo, đủ năng lực làm việc trong môi trường quốc tế.', 'http://apd.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, '(024) 3747 3186', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HCP.png?alt=media&token=41cc497f-a472-428e-9622-5f0f543cd0b1'),
       ('Học viện Công nghệ Bưu chính Viễn thông', 'BVH', 'Sáng tạo và chuyển giao tri thức cho xã hội thông qua việc gắn kết các hoạt động đào tạo nguồn nhân lực chất lượng cao, nghiên cứu phát triển và chuyển giao khoa học công nghệ trong lĩnh vực thông tin, truyền thông và công nghệ số, góp phần xây dựng đất nước Việt Nam hùng cường.', 'http://portal.ptit.edu.vn/', NULL, NULL,
        NULL, NULL, NULL, 'tuyensinh@ptit.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 33528122', NULL,
        '(024) 33512252', NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/BVH.png?alt=media&token=4a976091-29a8-4978-aad1-ef1abd45df0b'),
       ('Học viện Dân tộc', 'HVD', 'Học viện Dân tộc là cơ sở nghiên cứu khoa học, giáo dục công lập trực thuộc Ủy ban Dân tộc, hoạt động theo Điều lệ trường đại học. Học viện Dân tộc (Việt Nam) có chức năng nghiên cứu về công tác dân tộc, chiến lược và các chính sách dân tộc, đào tạo trình độ đại học, sau đại học, góp phần đào tạo đội ngũ cán bộ là người dân tộc thiểu số và cán bộ cho vùng dân tộc thiểu số và miền núi.', 'http://hvdt.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'hvdt@cema.gov.vn', NULL, NULL, NULL, NULL, NULL, '024.37831662', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HVD.png?alt=media&token=0eba5b41-dfcc-4ebd-a388-63f34cd82128'),
       ('Học viện Hành chính Quốc gia', 'HCH', 'Học viện Hành chính Quốc gia (tiền thân là: Trường Hành chính) là đơn vị sự nghiệp công lập trọng điểm hạng đặc biệt thuộc hệ thống giáo dục quốc dân trực thuộc Bộ Nội vụ. Đây là Học viện hệ công lập thuộc nhóm các trường Đại học, Học viện trọng điểm của Quốc gia Việt Nam và có tư cách pháp nhân, con dấu, tài khoản riêng tại Kho bạc Nhà Nước.', 'https://napa.vn/', NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, '043-8343223', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HCH.png?alt=media&token=9b6dcf12-cd77-4dd9-a44c-b5f9bb45f662'),
       ('Học viện Kỹ thuật Mật mã', 'KMA', 'Học viện Kỹ thuật Mật mã (KMA) là một trường đại học công lập trực thuộc Ban Cơ yếu Chính phủ của Bộ Quốc phòng, được thành lập ngày 17 tháng 2 năm 1995 có chức năng đào tạo cán bộ có trình độ đại học, sau đại học và nghiên cứu khoa học kỹ thuật mật mã của ngành Cơ yếu Việt Nam.', 'http://actvn.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'Support@actvn.edu.vn', NULL, NULL, NULL, NULL, NULL, '2438544244', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/KMA.jpg?alt=media&token=beffebe0-4d98-46c6-8fc9-88b41e1475b9'),
       ('Học viện Múa Việt Nam', 'HVM', 'Học viện Múa Việt Nam là cơ sở giáo dục công lập trong hệ thống giáo dục quốc dân trực thuộc Bộ Văn hóa - Thể thao và Du lịch; chịu sự quản lý nhà nước của Bộ Giáo dục và Đào tạo, Bộ Lao động - Thương binh và Xã hội, nằm trong địa chính trên địa bàn thành phố Hà Nội.', 'vnad.edu.vn', NULL, NULL, NULL, NULL, NULL,
        'hvmvn@vnad.edu.vn', NULL, 'hvmvn@bvhttdl.gov.vn', NULL, NULL, NULL, '024.3764.3546', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HVM.jpg?alt=media&token=c1c4b682-7e3d-429f-97c0-30a7601f4f9b'),
       ('Học viện Ngân hàng', 'NHH', 'Học viện Ngân hàng được thành lập từ năm 1961. Học viện Ngân hàng là trường đại học công lập đa ngành trực thuộc Ngân hàng Nhà nước Việt Nam và Bộ Giáo dục & Đào tạo, Học viện có trụ sở chính tại Hà Nội, phân viện Bắc Ninh, phân viện Phú Yên, phân viện Thành phố Hồ Chí Minh (tồn tại đến năm 2003) và cơ sở đào tạo Sơn Tây với hơn 16.000 sinh viên đang theo học.', 'http://hvnh.edu.vn', NULL, NULL, NULL, NULL, NULL,
        'truyenthong@hvnh.edu.vn', NULL, NULL, NULL, NULL, NULL, '1900 561 595', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NHH.jpg?alt=media&token=a4276dc4-010a-4607-8a74-5d542b94ef68'),
       ('Học viện Ngoại giao', 'HQT', 'Học viện Ngoại giao là đơn vị sự nghiệp hệ công lập thuộc hệ thống giáo dục quốc dân trực thuộc Bộ Ngoại giao tại Việt Nam được Thường vụ Hội đồng Chính phủ ra quyết định thành lập năm 1959, cơ sở nghiên cứu – đào tạo đầu ngành thực hiện chức năng nghiên cứu chiến lược về quan hệ quốc tế và chính sách đối ngoại; đào tạo đại học, sau đại học và bồi dưỡng nghiệp vụ đối ngoại ở Việt Nam.', 'https://dav.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'bbtwebsite_dav@mofa.gov.vn', NULL, NULL, NULL, NULL, NULL, '(84-24) 3834 4540', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HQT.png?alt=media&token=2f254ed5-d118-4438-b225-396f3d706a83'),
       ('Học viện Nông nghiệp Việt Nam', 'HVN', 'Học viện Nông nghiệp Việt Nam, tiền thân là Trường Đại học Nông nghiệp 1 - Hà Nội, là Học viện chuyên ngành đứng đầu về đào tạo nhóm ngành nông - lâm - ngư nghiệp tại Miền Bắc Việt Nam, thuộc nhóm ba mươi trường đại học đứng đầu Đông Nam Á, thuộc nhóm các trường Đại học, Học viện trọng điểm của Quốc gia Việt Nam.', 'https://www.vnua.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'webmaster@vnua.edu.vn', NULL, NULL, NULL, NULL, NULL, '84.024.62617586', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HVN.jpg?alt=media&token=8767ecd5-efee-4051-ab24-2b4638db0c1b'),
       ('Học viện Phụ nữ Việt Nam', 'HPN', 'Học viện Phụ nữ Việt Nam là cơ sở giáo dục đại học công lập được thành lập theo Quyết định 1558/QĐ-TTg ngày 18 tháng 10 năm 2012 của Thủ tướng Chính phủ.[2] Kế thừa sự phát triển lịch sử 60 năm với tên gọi cũ là Trường Cán bộ Phụ nữ Trung ương, Học viện Phụ nữ Việt Nam tổ chức đào tạo, bồi dưỡng đội ngũ cán bộ Hội Liên hiệp Phụ nữ các cấp, cán bộ nữ cho hệ thống chính trị.', 'http://hvpnvn.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'vwa@vwa.edu.vn', NULL, NULL, NULL, NULL, NULL, '84-243 7759907', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HPN.jpg?alt=media&token=71b3f81e-27df-4d8b-981b-0be745a194ff'),
       ('Học viện Quản lý Giáo dục', 'HVQ', 'Trường hiện đang tập trung đào tạo 5 ngành: Quản lý giáo dục, Tâm lý học giáo dục, Kinh tế giáo dục, Giáo dục học và Công nghệ thông tin, đồng thời kết hợp công tác nghiên cứu các đề tài, đề án về khoa học giáo dục. Đây được coi là một trường đầu ngành về khoa học quản lý giáo dục trong hệ thống các trường đại học tại Việt Nam', 'https://naem.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'hvqlgd@moet.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.3864.3352', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HVQ.png?alt=media&token=358185b5-1225-4837-9597-787003926d14'),
       ('Học viện Tài chính', 'HTC', 'Học viện Tài chính trực thuộc Bộ Tài chính và chịu sự quản lý nhà nước của Bộ Giáo dục và Đào tạo, là một trong những trường đại học công lập hàng đầu thuộc khối kinh tế tại Việt Nam, trường nổi tiếng với thế mạnh trong việc đào tạo chuyên sâu về ngành Tài chính - Kế toán.', 'https://hvtc.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'hocvientaichinh@hvtc.edu.vn', NULL, NULL, NULL, NULL, NULL, '0243.8389326', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HTC.jpg?alt=media&token=62cc6783-e399-4b96-83dc-f985b763c487'),
       ('Học viện Thanh Thiếu niên Việt Nam', 'HTN', 'Học viện Thanh Thiếu niên Việt Nam là một Học viện hệ Công lập đào tạo với vai trò bồi dưỡng tư cách đạo đức, lý luận chính trị cho thanh niên Việt Nam. Trường có 2 cơ sở tại Miền Bắc (tại Thủ đô Hà Nội) và Miền Nam (tại thành phố Hồ Chí Minh). Học viện trực thuộc Đoàn Thanh niên Cộng sản Hồ Chí Minh.', 'http://vya.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'daotao@vya.edu.vn', NULL, NULL, NULL, NULL, NULL, '0243. 834 3837', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HTN.png?alt=media&token=fb645e45-24f1-4cb1-80c4-fed81d9dfe35'),
       ('Học viện Tòa án', 'HTA', 'Học viện Tòa án là cơ sở giáo dục hàm Học viện hệ công lập thuộc hệ thống giáo dục quốc dân trực thuộc Tòa án Nhân dân Tối cao, Nhà trường hoạt động theo Luật Tổ chức Tòa án nhân dân, Luật Giáo dục đại học, Luật Giáo dục nghề nghiệp và Điều lệ trường đại học. Học viện Tòa án có tư cách pháp nhân, có con dấu và tài khoản riêng theo quy định của pháp luật.', 'http://hvta.toaan.gov.vn', NULL, NULL, NULL, NULL, NULL,
        'hvta@toaan.gov.vn', NULL, NULL, NULL, NULL, NULL, '0432.693.693', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HTA.jpg?alt=media&token=35703f23-9474-4599-ae19-72f5128ae0f6'),
       ('Học viện Y Dược học cổ truyền Việt Nam', 'HYD', 'Học viện Y – Dược học cổ truyền Việt Nam là một trường đại học chuyên ngành y khoa tại Việt Nam. Có sứ mạng đào tạo bác sĩ, dược sĩ có trình độ đại học, sau đại học, nghiên cứu khoa học và chuyển giao công nghệ y dược, hỗ trợ phát triển hệ thống y tế nhằm đáp ứng nhu cầu chăm sóc sức khỏe cho nhân dân khu vực Đồng bằng sông Hồng. Trường trực thuộc Bộ Y tế.', 'http://vutm.edu.vn', NULL, NULL, NULL, NULL,
        NULL, 'hocvienyduoc@vutm.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84-24) 3382 4929', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HYD.jpg?alt=media&token=735116d3-e551-4087-b337-34e2226587af'),
       ('Trường Đại học CMC', 'CMC', 'Trường Đại học CMC hướng tới xây dựng mô hình trường Đại học thông minh đầu tiên tại Việt Nam, là nơi tất cả sinh viên đều được tự do lựa chọn định hướng cho bản thân, đánh thức và phát triển tiềm năng tối đa để tự tin trở thành công dân toàn cầu, sẵn sàng thích ứng với mọi biến đổi trong thế giới số 4.0, tạo ra những đột phá trong khoa học công nghệ để kiến tạo tương lai và đóng góp cho cộng đồng.', 'https://cmc-u.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'tuyensinh@cmc-u.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 7102 9999', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/CMC.png?alt=media&token=9d18eb75-ce91-4f5f-ad51-463a4a503821'),
       ('Trường Đại học Công đoàn', 'LDA', 'Trường Đại học Công đoàn là một trường Đại học Công lập lâu đời trong hệ thống các trường Đại học Việt Nam, trực thuộc Tổng Liên đoàn Lao động Việt Nam. Trường Đại học Công đoàn là cơ sở giáo dục Đại học định hướng nghiên cứu, đào tạo đa ngành, đa lĩnh vực và là trường đầu ngành trong lĩnh vực công đoàn, quan hệ lao động, công tác xã hội và quản trị nhân lực.', 'http://www.dhcd.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'dhcongdoan@dhcd.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84-4) 3.857.3204', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/LDA.png?alt=media&token=105362b6-91ef-4d56-ae7c-66d880e689f3'),
       ('Trường Đại học Công nghệ Giao thông vận tải', 'GTA', 'Trường Đại học Công nghệ Giao thông vận tải có sứ mạng đào tạo và cung cấp nguồn nhân lực chất lượng cao theo hướng ứng dụng, đa ngành, đa lĩnh vực, nghiên cứu khoa học và chuyển giao công nghệ phục vụ sự nghiệp phát triển của ngành Giao thông vận tải và của đất nước, phù hợp với xu thế phát triển quốc tế, hội nhập với nền giáo dục đại học tiên tiến của khu vực và trên thế giới', 'http://utt.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'infohn@utt.edu.vn', NULL, NULL, NULL, NULL, NULL, '0243.854 4264', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/GTA.png?alt=media&token=1e22cb44-717e-4ea5-b5be-a504ff49b30f'),
       ('Trường Đại học Công nghệ và Quản lý Hữu nghị', 'DCQ', 'Trường hướng tới mục tiêu trở thành trường đại học đào tạo đa ngành, đa lĩnh vực, cung cấp nguồn nhân lực chất lượng cao cho thị trường trong nước và quốc tế với phương châm khác biệt và chất lượng.', 'http://utm.edu.vn', NULL, NULL, NULL,
        NULL, NULL, 'contact@utm.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 36 320743', NULL, '(024) 37 632 890',
        NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DCQ.jpg?alt=media&token=66c1c11d-1cd6-4cb7-b0bf-ebe7cf1e5e51'),
       ('Trường Đại học Công nghiệp Dệt may Hà Nội', 'CCM', 'Đào tạo nguồn nhân lực định hướng ứng dụng có khả năng làm việc độc lập, sáng tạo, chuyên nghiệp trong môi trường toàn cầu; có năng lực nghiên cứu, tổ chức sản xuất thử nghiệm và chuyển giao công nghệ phục vụ ngành công nghiệp, đặc biệt là lĩnh vực dệt may.', 'http://hict.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'phongtchc@hict.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.38276514', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/CCM.png?alt=media&token=58c98ead-b6de-4463-a840-415ca89dcbeb'),
       ('Trường Đại học Công nghiệp Hà Nội', 'DCN', 'Đào tạo nhân lực chất lượng cao; sáng tạo và chuyển giao tri thức, công nghệ tới xã hội và cộng đồng đáp ứng yêu cầu thời kỳ cách mạng công nghiệp, phục vụ xã hội và đất nước.', 'https://www.haui.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'dhcnhn@haui.edu.vn', NULL, NULL, NULL, NULL, NULL, '+84 243 765 5121', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DCN.jpg?alt=media&token=eb8ee238-0c95-4d46-a029-febc441767d3'),
       ('Trường Đại học Công nghiệp Việt Hung', 'VHD', 'Đào tạo 8 ngành đại học, 12 ngành cao đẳng thuộc 02 nhóm ngành: Công nghệ kĩ thuật và Kinh tế.', 'http://viu.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'viethung@viu.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 33838345', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/VHD.png?alt=media&token=e21b6688-a43a-4615-b6de-7851eaccdae9'),
       ('Trường Đại học Dược Hà Nội', 'DKH', '   Trường Đại học Dược Hà Nội tiền thân từ Trường thuốc Đông Dương thành lập năm 1902. Năm 1961, Trường được tách ra từ Trường Đại học Y Dược thành Trường Đại học Dược khoa và nay là Trường Đại học Dược Hà Nội.', 'http://www.hup.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'info@hup.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 382-545-39', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DKH.jpg?alt=media&token=2a8ba750-c4f9-40b7-90f7-8a4095e6967e'),
       ('Trường Đại học Đại Nam', 'DDN', 'Đào tạo để người học ra trường có cuộc sống tốt và là công dân tốt; góp phần thúc đẩy mạnh mẽ nền giáo dục đại học nước nhà', 'https://www.dainam.edu.vn/vi', NULL, NULL, NULL, NULL, NULL,
        'dnu@dainam.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 35577799', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DDN.png?alt=media&token=23039221-4ea3-44e8-9ae9-28f0372b3fdd'),
       ('Trường Đại học Điện lực', 'DDL', 'Trường Đại học Điện lực là trường đại học công lập đa ngành, đào tạo nguồn nhân lực chất lượng cao; nghiên cứu khoa học, phát triển công nghệ, tư vấn chính sách, chuyển giao tri thức, đặc biệt trong lĩnh vực năng lượng, góp phần xây dựng, phát triển đất nước và hội nhập quốc tế.', 'https://www.epu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'info@epu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 2245 2662', NULL, '(024) 2218 5629', NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DDL.jpg?alt=media&token=38c68016-aeea-4bd1-a299-b089c8afcf6d'),
       ('Trường Đại học Đông Đô', 'DDD', 'Trường Đại học Đông Đô là một trong những đại học tư thục được thành lập sớm nhất tại Việt Nam (từ năm 1994), trụ sở của Trường được đặt tại Thủ đô Hà Nội.', 'http://www.hdiu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'contact@hdiu.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 3771 9960', NULL, '024 3771 9961', NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DDD.png?alt=media&token=8eecdb8b-4801-4fb4-91da-c07ed6ef3175'),
       ('Trường Đại học FPT', 'FPT', 'Sự khác biệt của Trường Đại học FPT so với các trường đại học khác là đào tạo theo hình thức liên kết chặt chẽ với các doanh nghiệp, gắn đào tạo với thực tiễn, với nghiên cứu – triển khai và các công nghệ hiện đại nhất. Triết lý và phương pháp giáo dục hiện đại; Đào tạo con người toàn diện, hài hòa; Chương trình luôn được cập nhật và tuân thủ các chuẩn công nghệ quốc tế; Đặc biệt chú trọng kỹ năng ngoại ngữ; Tăng cường đào tạo quy trình tổ chức sản xuất, kỹ năng làm việc theo nhóm và các kỹ năng cá nhân khác là những điểm sẽ đảm bảo cho sinh viên tốt nghiệp có những cơ hội việc làm tốt nhất sau khi ra trường.', 'https://hanoi.fpt.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'tuyensinhfpt@gmail.com', NULL, NULL, NULL, NULL, NULL, '(024) 7300.1866', NULL, '(024) 7300.5588', NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/FPT.png?alt=media&token=feb46154-5367-45cd-8de2-61d0b8eca869'),
       ('Trường Đại học Giao thông vận tải', 'GHA', 'Trường Đại học Giao thông vận tải hướng tới mô hình đại học đa ngành về kỹ thuật, công nghệ và kinh tế; trở thành đại học trọng điểm, đào tạo nguồn nhân lực có trình độ cao đáp ứng nhu cầu phát triển bền vững ngành giao thông vận tải và đất nước; là trung tâm nghiên cứu khoa học có uy tín về Giao thông vận tải và một số lĩnh vực khác; có đẳng cấp trong khu vực và hội nhập Quốc tế; là địa chỉ tin cậy của người học, nhà đầu tư và toàn xã hội.', 'https://www.utc.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'dhgtvt@utc.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84.24) 37663311', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/GHA.jpg?alt=media&token=8911cc01-8e49-4888-9340-1b9e5d222381'),
       ('Trường Đại học Hà Nội', 'NHF', 'Trường Đại học Hà Nội đào tạo nguồn nhân lực chất lượng cao thành thạo ngoại ngữ, nghiên cứu khoa học, chuyển giao công nghệ theo xu thế hội nhập, góp phần thúc đẩy sự phát triển bền vững của xã hội và của đất nước.', 'https://hanu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'hanu@hanu.edu.vn', NULL, 'tuyensinh@hanu.edu.vn', NULL, NULL, NULL, '(84-24) 38544338', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NHF.jpg?alt=media&token=6cabf7d7-70fc-41cf-8e9f-401ef874ee41'),
       ('Trường Đại học Hòa Bình', 'HBU', 'Đào tạo nguồn nhân lực chất lượng cao có nền tảng kiến thức vững chắc, có năng lực đổi mới sáng tạo, thích ứng với môi trường làm việc toàn cầu, có trách nhiệm với bản thân, gia đình, cộng đồng, xã hội và toàn nhân loại, góp phần xây dựng Việt Nam phồn vinh, đậm đà bản sắc dân tộc.', 'http://daihochoabinh.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'peaceuniv@daihochoabinh.edu.vn', NULL, NULL, NULL, NULL, NULL, '0247.109.9669', NULL, '0981.969.288', NULL,
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HBU.png?alt=media&token=02a9bc91-5f3a-4a0b-85d0-98dc5023857c'),
       ('Trường Đại học Khoa học và Công nghệ Hà Nội', 'KCN', 'USTH có sứ mệnh đào tạo nguồn nhân lực chất lượng cao trong lĩnh vực khoa học – công nghệ – kỹ thuật, nhằm phát triển nghiên cứu và đẩy mạnh chuyển giao công nghệ. Tận dụng mối quan hệ hợp tác chặt chẽ với Pháp, Trường phải đón đầu xu hướng thay đổi của công nghệ trong tương lai ở châu Á và trở thành trường đại học uy tín về nghiên cứu khoa học công nghệ tại Đông Nam Á trong thời đại công nghệ 4.0.', 'https://www.usth.edu.vn/', NULL, NULL,
        NULL, NULL, NULL, 'officeusth@usth.edu.vn', NULL, 'webmaster@usth.edu.vn', NULL, NULL, NULL,
        '+84-24 37 91 69 60', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/KCN.png?alt=media&token=6da90d8e-8840-40e7-ba2e-62a734dd2871'),
       ('Trường Đại học Kinh doanh và Công nghệ Hà Nội', 'DQK', 'Trường Đại học Kinh doanh và Công nghệ Hà Nội là một tổ chức hợp tác của những người lao động trí óc, tự nguyện góp sức, góp vốn hoạt động vì sự nghiệp “trồng người” không vì mục đích lợi nhuận, đào tạo các nhà quản lý kinh tế và kỹ thuật – công nghệ thực hành, các cán bộ y dược có tay nghề cao, tạo nguồn nhân lực cho việc hình thành một đội ngũ cán bộ chủ chốt của các tổ chức, đơn vị doanh nghiệp trong phát triển kinh tế – xã hội, bảo vệ sức khỏe, phục vụ sự nghiệp công nghiệp hóa, hiện đại hóa đất nước theo mục tiêu dân giầu, nước mạnh, xã hội công bằng, dân chủ, văn minh.', 'http://hubt.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'vanphong@hubt.edu.vn', NULL, NULL, NULL, NULL, NULL, '04.36336605', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DQK.jpg?alt=media&token=35227761-fe7b-46eb-858e-fcfa692c01cc'),
       ('Trường Đại học Kinh tế Kỹ thuật Công nghiệp', 'DKK', 'Trường Đại học Kinh tế – Kỹ thuật Công nghiệp là cơ sở giáo dục đại học định hướng ứng dụng hoạt động theo cơ chế tự chủ; thực hiện các chức năng giáo dục – đào tạo, nghiên cứu khoa học, phục vụ cộng đồng đáp ứng mục tiêu xã hội và yêu cầu Công nghiệp hóa – Hiện đại hóa đất nước.', 'http://uneti.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'web@uneti.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.38621504', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DKK.png?alt=media&token=2c6776ed-9b0c-4ebe-8603-b3b4a308241c'),
       ('Trường Đại học Kinh tế Quốc dân', 'KHA', 'Tiên phong trong đổi mới, phát triển và phổ biến tri thức về kinh tế, quản lý và quản trị kinh doanh; thu hút và đào tạo nhân tài; cung cấp nguồn nhân lực chất lượng cao, phụng sự sự nghiệp phát triển bền vững của đất nước.', 'https://www.neu.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'cnttkt@neu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84)24.36.280.280', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/KHA.jpg?alt=media&token=99da270f-97e8-4c18-a5db-cd723d574361'),
       ('Trường Đại học Kiểm sát Hà Nội', 'DKS', 'Trường Đại học Kiểm sát Hà Nội là cơ sở giáo dục đại học công lập trong hệ thống giáo dục quốc dân Việt Nam, trực thuộc Viện Kiểm sát Nhân dân tối cao.', 'https://hpu.vn/', NULL, NULL, NULL, NULL, NULL,
        'contact@tks.edu.vn', NULL, NULL, NULL, NULL, NULL, '0243.358.0467', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DKS.png?alt=media&token=42a8f4f1-dbf8-4c26-b56b-9aafcd835ada'),
       ('Trường Đại học Kiến trúc Hà Nội', 'KTA', 'Trường Đại học Kiến trúc được thành lập theo Quyết định số 181/CP ngày 17 tháng 9 năm 1969 của Hội đồng Chính phủ. Trường thuộc Bộ Xây dựng, chịu sự quản lý Nhà nước về chuyên môn của Bộ Giáo dục và Đào tạo và sự quản lý hành chính theo lãnh thổ của Ủy ban Nhân dân thành phố Hà Nội.', 'http://www.hau.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, '024. 3854 1616', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/KTA.png?alt=media&token=b0f62b6d-13bd-4e27-a4be-46706b0a1fe8'),
       ('Trường Đại học Lao động Xã hội', 'DLX', 'Đào tạo nhân lực trình độ cử nhân các khối ngành kinh tế, xã hội; nghiên cứu và ứng dụng khoa học phục vụ giáo dục, đào tạo và phát triển kinh tế - xã hội', 'http://www.ulsa.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, '043.5564584', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DLX.png?alt=media&token=e70e8358-c6e3-4247-9516-cae128fb0b77'),
       ('Trường Đại học Lâm nghiệp', 'LNH', 'Là cơ sở giáo dục đại học hàng đầu về đào tạo, cung cấp nguồn nhân lực chất lượng cao, nghiên cứu và phát triển, chuyển giao khoa học công nghệ về lĩnh vực lâm nghiệp, tài nguyên môi trường, kỹ thuật, công nghệ, kinh tế chính sách và quản lý, góp phần quan trọng vào sự nghiệp công nghiệp hóa, hiện đại hóa đất nước.', 'https://vnuf.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'vnuf@vnuf.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.33840233', NULL, '024.33840440', NULL, '024.33840707',
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/LNH.png?alt=media&token=e949805b-839c-4080-832d-8c375d1f16bf'),
       ('Trường Đại học Luật Hà Nội', 'LPH', 'Trường Đại học Luật Hà Nội là trường đại học có quy mô đào tạo về ngành luật lớn nhất ở Việt Nam hiện nay, thực hiện nhiệm vụ đào tạo nguồn nhân lực pháp luật chất lượng cao cho đất nước. Trường đang tổ chức đào tạo các bậc đại học, cao học, và nghiên cứu sinh; Ngoài ra với nhu cầu của xã hội, Trường tổ chức lớp bồi dưỡng kiến thức pháp luật cho nhiều đối tượng khác nhau. Thực hiện, tổ chức nghiên cứu, ứng dụng khoa học pháp lý và thực hiện nhiệm vụ khác do Bộ trưởng Bộ Tư pháp và Bộ Giáo dục và Đào tạo giao.', 'http://hlu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'admin@hlu.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.38352630', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/LPH.jpg?alt=media&token=a47ca76c-d350-466a-9c1d-6dcdc253faed'),
       ('Trường Đại học Mỏ Địa chất Hà Nội', 'MDA', 'Đào tạo nguồn nhân lực chất lượng cao, nghiên cứu khoa học và chuyển giao tri thức - công nghệ đáp ứng nhu cầu xã hội và hội nhập quốc tế. ', 'https://humg.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'hanhchinhtonghop@humg.edu.vn', NULL, NULL, NULL, NULL, NULL, '(+84-24) 3838 9633', NULL, NULL, NULL,
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/MDA.jpg?alt=media&token=3e1f24b7-3b33-45e9-8e98-53c1a23e9886'),
       ('Trường Đại học Mở Hà Nội', 'MHN', 'Mở cơ hội học tập cho mọi người với chất lượng tốt, đáp ứng nhu cầu học tập đa dạng với nhiều loại hình, chú trọng giáo dục từ xa, đa ngành, đa trình độ, phục vụ sự nghiệp xây dựng đất nước và hội nhập quốc tế.', 'https://hou.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'mhn@hou.edu.vn', NULL, NULL, NULL, NULL, NULL, '024 38682321', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/MHN.jpg?alt=media&token=5fcd10ff-f5c8-4080-92f0-4c422bca735c'),
       ('Trường Đại học Mỹ thuật Công nghiệp', 'MTC', 'Trường đại học Mỹ thuật Công nghiệp – tiền thân là trường Quốc gia Mỹ nghệ được thành lập ngày 8 tháng 7 năm 1949. Quá trình hình thành, xây dựng và phát triển của trường đại học Mỹ thuật Công nghiệp qua hai thế kỷ được kết nối bởi nhiều giai đoạn lịch sử, phản ánh sự đi lên, trưởng thành theo những quy luật chung tất yếu, khách quan, đồng thời cho thấy sự tích cực chủ động nỗ lực phấn đấu vươn lên của các thế thệ cán bộ, giảng viên, nhân viên, sinh viên, học viên đối với sự nghiệp xây dựng, củng cố, phát triển từ giai đoạn đầu thành lập cho đến ngày nay và những năm tiếp theo', 'https://uad.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'mtcn@gmail.com', NULL, NULL, NULL, NULL, NULL, '024 38512476', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/MTC.jpg?alt=media&token=ec3f9b1d-3e48-4743-9b52-c7c2965c16bc'),
       ('Trường Đại học Mỹ thuật Việt Nam', 'MTH', 'Tạo lập và phát triển môi trường đào tạo, nghiên cứu và sáng tác mỹ thuật chuyên nghiệp, phát huy tốt nhất tiềm năng sáng tạo của người học; bồi dưỡng nhân tài và cung cấp nguồn nhân lực chất lượng cao phục vụ cho sự nghiệp nghệ thuật, đáp ứng yêu cầu phát triển văn hóa, kinh tế - xã hội của đất nước trong thời kỳ Cách mạng công nghiệp 4.0.', 'http://mythuatvietnam.edu.vn/', NULL, NULL, NULL,
        NULL, NULL, 'quantriweb@mythuatvietnam.edu.vn', NULL, NULL, NULL, NULL, NULL, '(844) 39426972', NULL, NULL,
        NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/MTH.png?alt=media&token=a71eadf3-f047-4f49-9f8c-2c8078656959'),
       ('Trường Đại học Ngoại thương', 'NTH', 'Đào tạo và nghiên cứu: từ các ngành truyền thống và có thế mạnh về kinh tế, kinh doanh thuộc các lĩnh vực Khoa học xã hội và hành vi (ngành Kinh tế, ngành Kinh tế quốc tế), Kinh doanh và quản lý (ngành Quản trị kinh doanh, ngành Kế toán, ngành Tài chính - Ngân hàng, ngành Kinh doanh quốc tế), Nhân văn (ngành Ngôn ngữ Anh, ngành Ngôn ngữ Nhật, ngành Ngôn ngữ Trung, ngành Ngôn ngữ Pháp), Pháp luật (ngành Luật), Du lịch và Khách sạn (Quản trị khách sạn), Nhà trường tiếp tục phát triển thêm các ngành mới thuộc các lĩnh vực trên và các ngành sang các lĩnh vực mới, như lĩnh vực Máy tính và Công nghệ thông tin; Báo chí và thông tin; Nghệ thuật và một số lĩnh vực khác.', 'http://www.ftu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'qldt@ftu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84-24) 3259 5158', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NTH.png?alt=media&token=f8f242db-0b6d-46dc-a860-0277b4f3ee6d'),
       ('Trường Đại học Nguyễn Trãi', 'NTU', 'Trường Đại học Nguyễn Trãi là một cơ sở kinh doanh dịch vụ giáo dục tại Việt Nam, được thành lập ngày 5/2/2008 theo Quyết định số 183/QĐ-TTg của Thủ tướng Chính phủ, tiền thân của trường hiện nay là Viện Đào tạo Công nghệ và Quản lý Quốc tế.', 'https://daihocnguyentrai.edu.vn/', NULL, NULL, NULL, NULL,
        NULL, 'daihocnguyentrai@gmail.com', NULL, NULL, NULL, NULL, NULL, '981924302', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/NTU.png?alt=media&token=2f63259e-f9b3-4000-ad4f-38d2da722b8c'),
       ('Trường Đại học Nội vụ Hà Nội', 'DNV', 'Trường Đại học Nội vụ Hà Nội là đơn vị sự nghiệp công lập được thành lập vào năm 1971 trực thuộc Bộ Nội vụ. Được đổi tên thành Trường Đại học Nội vụ Hà Nội vào ngày 14 tháng 11 năm 2011 trên cơ sở nâng cấp từ Trường Cao đẳng Nội vụ Hà Nội.', 'http://www.truongnoivu.edu.vn', NULL,
        'http://www.huha.edu.vn', NULL, NULL, NULL, 'hotrokythuat@huha.edu.vn', NULL, NULL, NULL, NULL, NULL,
        '+84-24-37532864', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DNV.jpg?alt=media&token=6fec94ed-cb6a-436b-a353-6a3d5ef7437a'),
       ('Trường Đại học Phenikaa', 'PKA', 'Trường Đại học Phenikaa đang từng bước xây dựng một môi trường học thuật theo hướng quốc tế hóa, song song với việc đẩy mạnh các hoạt động hợp tác nghiên cứu, các dự án, các hội nghị - hội thảo quốc tế, tăng cường các chương trình trao đổi sinh viên, giảng viên cũng như thúc đẩy hợp tác với các trường đại học và viện nghiên cứu khác trên toàn thế giới, nhằm trao đổi và chia sẻ kinh nghiệm giáo dục, nghiên cứu và phát triển.', 'http://phenikaa-uni.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'Info@phenikaa-uni.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.62918118', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/PKA.png?alt=media&token=36a500f3-64b7-4f14-8758-51176b57ca79'),
       ('Trường Đại học Phương Đông', 'DPD', 'Trường Đại học Phương Đông được thành lập năm 1994, đào tạo khoảng 9.000 sinh viên tại 6 khoa và 1 trung tâm, với 21 ngành bậc đại học, 4 ngành bậc cao đẳng. Trường sẽ bắt đầu đào tạo trình độ Thạc sĩ cho 2 ngành từ năm 2013.', 'http://phuongdong.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'tuyensinh@phuongdong.edu.vn', NULL, NULL, NULL, NULL, NULL, '024-3784-8513 (14/15/16/17/18)', NULL, NULL, NULL,
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DPD.png?alt=media&token=20e6214d-c804-4a85-b6c2-c7768170d9dc'),
       ('Trường Đại học Sân khấu Điện ảnh', 'SKD', 'Trường có các khoa đào tạo chuyên ngành diễn viên sân khấu – điện ảnh; đạo diễn sân khấu – điện ảnh; thiết kế; nhiếp ảnh; quay phim; biên kịch; hóa trang… với những giảng viên chuyên ngành, đam mê với nghề, tích lũy nhiều kinh nghiệm cùng các chương trình đào tạo đa dạng (như bồi dưỡng kiến thức; trung cấp; cao đẳng; Đại học; sau đại học) với mức độ chuyên sâu khác nhau, phù hợp với từng chuyên ngành theo từng chương trình.', 'http://skda.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'info@skda.edu.vn', NULL, NULL, NULL, NULL, NULL, '02437643397', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/SKD.png?alt=media&token=dd679f79-e892-40ba-bb69-fc235bd80195'),
       ('Trường Đại học Sư phạm Hà Nội', 'SPH', 'Trường Đại học Sư phạm Hà Nội là trường đại học trọng điểm quốc gia và khu vực, đào tạo các chuyên gia xuất sắc có đóng góp đặc biệt quan trọng cho hệ thống giáo dục và xã hội thông qua các chương trình nghiên cứu, hợp tác đào tạo đại học và sau đại học có chất lượng cao.', 'http://www.hnue.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'p.hcth@hnue.edu.vn', NULL, NULL, NULL, NULL, NULL, '024.37547823', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/SPH.jpg?alt=media&token=0a28a82d-5855-40f4-b29f-4c0f0c7cd68e'),
       ('Trường Đại học Sư phạm Nghệ thuật Trung ương Hà Nội', 'GNT', 'Trường Đại học Sư phạm Nghệ thuật Trung ương là cơ sở đào tạo, bồi dưỡng nguồn nhân lực có trình độ đại học, sau đại học và nghiên cứu khoa học, chuyển giao công nghệ trong lĩnh vực Văn hóa, Giáo dục nghệ thuật, trực thuộc Bộ Giáo dục và Đào tạo.', 'http://www.spnttw.edu.vn/', NULL,
        NULL, NULL, NULL, NULL, 'spnttw@spnttw.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84) 024.38544468', NULL, NULL,
        NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/GNT.png?alt=media&token=89dd5564-47bd-43da-afcb-e56900e8b275'),
       ('Trường Đại học Sư phạm Thể dục thể thao Hà nội', 'TDH', NULL, 'https://hupes.edu.vn/', NULL, NULL,
        NULL, NULL, NULL, 'tdh@moet.edu.vn', NULL, 'tuyensinh.tdh@gmail.com', NULL, NULL, NULL, '(024) 33866 058', NULL,
        NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TDH.png?alt=media&token=65803e94-e78a-4093-a3f6-a026745fdc87'),
       ('Trường Đại học Tài chính Ngân hàng Hà Nội', 'FBU', NULL, 'https://www.fbu.edu.vn', NULL, NULL, NULL,
        NULL, NULL, 'fbu.tuyensinh@gmail.com', NULL, NULL, NULL, NULL, NULL, '024 3793 1340', NULL, '024 3793 1341',
        NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/FBU.png?alt=media&token=a9cca436-b782-4f16-89cd-320174e40564'),
       ('Trường Đại học Tài nguyên và Môi trường Hà Nội', 'DMT', NULL, 'https://hunre.edu.vn/', NULL, NULL,
        NULL, NULL, NULL, 'DHTNMT@hunre.edu.vn', NULL, NULL, NULL, NULL, NULL, '0902.130.130', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DMT.png?alt=media&token=f8bfcede-58a2-4d61-a498-b56e1b4c642b'),
       ('Trường Đại học Thăng Long', 'DTL', 'Trường Đại học Sư phạm TDTT Hà Nội là trường đại học công lập, thành lập năm 1961, tiền thân là trường TDTT, thuộc Bộ Giáo dục và Đào tạo. Là trường đầu tiên tại Việt Nam có nhiệm vụ đào tạo giáo viên TDTT trình độ đại học và sau đại học; Bồi dưỡng chuyên môn nghiệp vụ cho đội ngũ giáo viên TDTT; Nghiên cứu và ứng dụng khoa học giáo dục thể chất; Đào tạo kiến thức quốc phòng và an ninh cho sinh viên các trường đại học, cao đẳng, trung cấp chuyên nghiệp khu vực Hà Nội.', 'https://thanglong.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'info@thanglong.edu.vn', NULL, 'hopthugopy@thanglong.edu.vn', NULL, NULL, NULL, '024 3858 7346', NULL,
        '024 9999 1988', NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/DTL.jpg?alt=media&token=c35c962e-f15a-4d6e-953d-ead04526373c'),
       ('Trường Đại học Thành Đô', 'TDD', 'Được thành lập từ năm 2004, trải qua 20 năm hoạt động, Trường Đại học Thành Đô đã từng bước khẳng định vị thế là trường Đại học uy tín, đào tạo đa ngành, đa lĩnh vực với 4 khối ngành đào tạo', 'http://thanhdo.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'daihocthanhdo@thanhdouni.edu.vn', NULL, NULL, NULL, NULL, NULL, '0934 078 668', NULL, '0243 386 1601', NULL,
        NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TDD.png?alt=media&token=2451c34a-e4a7-442a-a88c-904feb2f8d3a'),
       ('Trường Đại học Thủ đô Hà Nội', 'HNM', 'Trường Đại học Thủ đô Hà Nội là trường đại học công lập đầu tiên do UBND thành phố Hà Nội trực tiếp quản lý thành lập ngày 31 tháng 12 năm 2014.', 'http://hnmu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'banbientap@hnmu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(+84) 24.3833.0708', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/HNM.png?alt=media&token=b08823d5-e352-4a29-9eb5-8f17210dee51'),
       ('Trường Đại học Thủy lợi', 'TLA', 'Là cơ sở giáo dục đại học đào tạo nguồn nhân lực, nghiên cứu, chuyển giao khoa học công nghệ chất lượng cao trong các lĩnh vực kỹ thuật, công nghệ, kinh tế đóng góp vào sự phát triển bền vững của đất nước.', 'http://www.tlu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'phonghcth@tlu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 38522201', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TLA.jpg?alt=media&token=52370882-e8d3-4151-a2a9-90630fa9c966'),
       ('Trường Đại học Thương mại', 'TMA', 'Đào tạo nhân lực chất lượng cao, trình độ cao, có năng lực khởi nghiệp và đổi mới sáng tạo, có khả năng cạnh tranh trên thị trường lao động trong nước và quốc tế; nghiên cứu khoa học, tư vấn chính sách, chuyển giao tri thức trong lĩnh vực kinh tế và thương mại hiện đại, đóng góp vào sự phát triển thịnh vượng và nâng cao vị thế của Việt Nam.', 'https://tmu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'mail@tmu.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 3764 3219', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/TMA.jpg?alt=media&token=8658f5ed-f574-4d2f-9754-0fd7a29f1a79'),
       ('Trường Đại học Văn hóa Hà Nội', 'VHH', 'Trường Đại học Văn hóa Hà Nội là cơ sở đào tạo và nghiên cứu các ngành thuộc lĩnh vực Nhân văn, Du lịch, Báo chí và Thông tin. Trường cung cấp nguồn nhân lực chất lượng cao, bồi dưỡng nhân tài, phục vụ cho sự nghiệp phát triển văn hóa, kinh tế - xã hội của đất nước.', 'http://www.huc.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'daihocvanhoahanoi@huc.edu.vn', NULL, NULL, NULL, NULL, NULL, '(+84) 2438.511.971', NULL, NULL, NULL, NULL,
        NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/VHH.jpg?alt=media&token=fd5f6861-371f-450e-a6d0-868073d7fbb6'),
       ('Trường Đại học Xây dựng Hà Nội', 'XDA', 'Đào tạo nhân lực chất lượng cao; nghiên cứu khoa học, sáng tạo công nghệ và chuyển giao tri thức; đồng kiến tạo vì sự phát triển bền vững của xã hội và đất nước.', 'https://huce.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'dhxaydung@huce.edu.vn', NULL, NULL, NULL, NULL, NULL, '(024) 38 696 397', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/XDA.jpg?alt=media&token=921e04be-506f-4f2f-8e66-33f61d2dbf67'),
       ('Trường Đại học Y Hà Nội', 'YHB', 'Không ngừng phấn đấu tạo ra các sản phẩm đào tạo, khoa học công nghệ và dịch vụ y tế tinh hoa, xứng đáng với truyền thống lịch sử hơn một thế kỷ phụng sự dân tộc.', 'http://hmu.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'daihocyhn@hmu.edu.vn', NULL, NULL, NULL, NULL, NULL, '+84 024 38523798', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/YHB.jpg?alt=media&token=1d788b48-89fc-4845-ae3c-7424edc1843a'),
       ('Trường Đại học Y tế Công cộng', 'YTC', 'Trường Đại học Y tế công cộng có sứ mạng đào tạo nguồn nhân lực, thực hiện nghiên cứu khoa học và cung cấp các dịch vụ chăm sóc sức khỏe, qua đó có những đóng góp quan trọng vào sự nghiệp chăm sóc, bảo vệ sức khoẻ nhân dân và phát triển kinh tế xã hội của đất nước', 'http://www.huph.edu.vn/', NULL, NULL, NULL, NULL, NULL,
        'ytcc@huph.edu.vn', NULL, NULL, NULL, NULL, NULL, '(84.4) 26266 2299', NULL, NULL, NULL, NULL, NULL,
        'https://firebasestorage.googleapis.com/v0/b/uniportal-32159.appspot.com/o/YTC.png?alt=media&token=b48f28a1-8149-41f3-a78f-e4b3c71f50cf');

INSERT INTO `address` (`house_number`, `street_name`, `description`, `ward_id`, `district_id`, `city_province_id`, `institution_id`)
VALUES ('268', 'Lý Thường Kiệt', NULL, '136', '9', '58', 1),
       ('Khu phố 6', 'Đường Hàn Thuyên', NULL, '15', '1', '58', 2),
       ('227', 'Nguyễn Văn Cừ', NULL, '73', '5', '58', 3),
       ('Khu đô thị Đại học Quốc gia Thành phố Hồ Chí Minh', 'nan', NULL, '16', '1', '58', 4),
       ('10-12', 'Đinh Tiên Hoàng', NULL, '35', '2', '58', 5),
       ('669, Khu phố 3', 'Quốc lộ 1', NULL, '16', '1', '58', 6),
       ('Khu phố 6', 'nan', NULL, '15', '1', '58', 7),
       ('15', 'Đường D5', NULL, '191', '13', '58', 8),
       ('217', 'Hồng Bàng', NULL, '80', '5', '58', 8),
       ('41', 'Đinh Tiên Hoàng', NULL, '35', '2', '58', 8),
       ('652', 'Nguyễn Trãi', NULL, '80', '5', '58', 8),
       ('221B', 'Hoàng Văn Thụ', NULL, '217', '15', '58', 8),
       ('201', 'Nguyễn Chí Thanh', NULL, '81', '5', '58', 8),
       ('159', 'Hưng Phú', NULL, '115', '8', '58', 9),
       ('59C', 'Nguyễn Đình Chiểu', 'Cơ sở A', '50', '3', '58', 9),
       ('279', 'Nguyễn Tri Phương', 'Cơ sở B', '127', '9', '58', 9),
       ('91', 'Ba Tháng Hai', 'Cơ sở C', '133', '9', '58', 9),
       ('196', 'Trần Quang Khải', 'Cơ sở D', '44', '2', '58', 9),
       ('54', 'Nguyễn Văn Thủ', 'Cơ sở E', '40', '2', '58', 9),
       ('1A', 'Hoàng Diệu', 'Cơ sở H', '219', '15', '58', 9),
       ('17', 'Phạm Ngọc Thạch', 'Cơ sở I', '50', '3', '58', 9),
       ('Khu chức năng số 15, Khu đô thị mới Nam thành phố', 'Đường Nguyễn Văn Linh', 'Cơ sở N', '259', '18', '58', 9),
       ('236/6', 'Võ Thị Sáu', 'Cơ sở V', '50', '3', '58', 9),
       ('144', 'Phạm Đức Sơn', 'Trung tâm thể dục thể thao UEH', '123', '8', '58',10),
       ('1', 'Võ Văn Ngân', NULL, '12', '1', '58',11),
       ('140', 'Lê Trọng Tấn', NULL, '249', '17', '58',12),
       ('12', 'Nguyễn Văn Bảo', NULL, '197', '14', '58',13),
       ('36', 'Nguyễn Hữu Thọ', NULL, '103', '7', '58',13),
       ('179A', 'Kha Vạn Cân', NULL, '14', '1', '58',14),
       ('450-451', 'Lê Văn Việt', NULL, '27', '1', '58',15),
       ('2', 'Võ Oanh', 'Cơ sở 1', '191', '13', '58',15),
       ('10, Khu phố 3', 'Đường số 12', 'Cơ sở 2', '1', '1', '58',15),
       ('70', 'Tô Ký', 'Cơ sở 3', '157', '11', '58',16),
       ('280', 'An Dương Vương', NULL, '73', '5', '58',17),
       ('36', 'Tôn Thất Đạm', 'Trụ sở chính', '42', '2', '58',17),
       ('39', 'Hàm Nghi', 'Cơ sở Hàm Nghi', '42', '2', '58',17),
       ('56', 'Hoàng Diệu II', 'Cơ sở Hoàng Diệu', '15', '1', '58',18),
       ('196', 'Pasteur', 'Cơ sở chính', '50', '3', '58',18),
       ('48', 'Đặng Văn Bi', 'Cơ sở Thủ Đức', '5', '1', '58',19),
       ('1018', 'Tô Ký', NULL, '157', '11', '58',20),
       ('97', 'Võ Văn Tần', 'Cơ sở 1', '50', '3', '58',20),
       ('35-37', 'Hồ Hảo Hớn', 'Cơ sở 2', '39', '2', '58',20),
       ('Khu dân cư Nhơn Đức', 'nan', 'Cơ sở 3', '309', '22', '58',20),
       ('2', 'Mai Thị Lựu', 'Cơ sở 4', '40', '2', '58',21),
       ('5', 'Phan Đăng Lưu', NULL, '177', '13', '58',22),
       ('10', 'Đường 3/2', 'Địa chỉ 1', '134', '9', '58',22),
       ('181', 'Lê Đức Thọ', 'Địa chỉ 2', '210', '14', '58',23),
       ('125', 'Cống Quỳnh', NULL, '41', '2', '58', 24),
       ('639', 'Nguyễn Trãi', 'Cơ sở 1', '80', '5', '58',24),
       ('KDC Nhơn Đức', 'nan', 'Cơ sở 2', '309', '22', '58',26),
       ('2', 'Trường Sa', NULL, '186', '13', '58',27),
       ('189', 'Nguyễn Oanh', NULL, '203', '14', '58',28),
       ('778', 'Nguyễn Kiệm', NULL, '214', '15', '58',29),
       ('236B', 'Lê Văn Sỹ', NULL, '224', '16', '58',30),
       ('19', 'Nguyễn Hữu Thọ', NULL, '103', '7', '58',31),
       ('51', 'Quốc Hương', 'Cơ sở 1', '30', '1', '58',31),
       ('288', 'Đỗ Xuân Hợp', 'Cơ sở 2', '23', '1', '58',32),
       ('Nhà E1, 144', 'Xuân Thủy', NULL, '328', '24', '24',33),
       ('Khu đô thị ĐHQGHN', 'nan', NULL, '777', '47', '24',33),
       ('Nhà E5, G7', 'Xuân Thủy', NULL, '328', '24', '24',33),
       ('Nhà C, E, Làng sinh viên HACINCO, 79', 'Ngụy Như Kon Tum', NULL, '419', '20', '24',33),
       ('Số 1', 'Trịnh Văn Bô', NULL, '478', '34', '24',34),
       ('E3, 144', 'Xuân Thủy', NULL, '328', '24', '24',35),
       ('Nhà G7, 144', 'Xuân Thủy', NULL, '328', '24', '24',36),
       ('334', 'Nguyễn Trãi', NULL, '423', '30', '24',37),
       ('336', 'Nguyễn Trãi', NULL, '423', '30', '24',38),
       ('Nhà E4, 144', 'Xuân Thủy', NULL, '328', '24', '24',39),
       ('Số 2', 'Phạm Văn Đồng', NULL, '328', '24', '24',40),
       ('nan', 'Lưu Hữu Phước', NULL, '469', '34', '24',41),
       ('Nhà Y1, 144', 'Xuân Thủy', NULL, '328', '24', '24',42),
       ('Số 1', 'Đại Cồ Việt', NULL, '363', '26', '24',43),
       ('77', 'Hào Nam', NULL, '394', '28', '24',44),
       ('36', 'Xuân Thủy', NULL, '328', '24', '24',45),
       ('65', 'Văn Miếu', NULL, '405', '28', '24',46),
       ('122', 'Hoàng Quốc Việt', NULL, '429', '31', '24',46),
       ('Km10', 'Nguyễn Trãi', NULL, '439', '32', '24',47),
       ('Khu đô thị Dream Town', '70', NULL, '476', '34', '24',48),
       ('77', 'Nguyễn Chí Thanh', NULL, '391', '28', '24',49),
       ('141', 'Chiến Thắng', NULL, '813', '49', '24',50),
       ('103', 'Hồ Tùng Mậu', NULL, '329', '24', '24',51),
       ('12', 'Chùa Bộc', NULL, '397', '28', '24',52),
       ('69', 'Chùa Láng', NULL, '391', '28', '24',53),
       ('nan', 'nan', NULL, '582', '39', '24',54),
       ('68', 'Nguyễn Chí Thanh', NULL, '324', '23', '24', 55),
       ('31', 'Phan Đình Giót', NULL, '420', '30', '24',56),
       ('58', 'Lê Văn Hiển', NULL, '427', '31', '24',56),
       ('58', 'Nguyễn Chí Thanh', NULL, '391', '28', '24',57),
       ('nan', '282', NULL, '603', '39', '24',58),
       ('2', 'Trần Phú', NULL, '439', '32', '24',59),
       ('CMC Tower, Số 11', 'Duy Tân', NULL, '328', '24', '24',60),
       ('84C', 'Nguyễn Thanh Bình', NULL, '444', '32', '24',60),
       ('Lô C3 cụm trường THCN', 'nan', NULL, '476', '34', '24',60),
       ('Vạn Phúc Building', 'Tố Hữu', NULL, '816', '49', '24',60),
       ('169', 'Tây Sơn', NULL, '397', '28', '24',61),
       ('54', 'Triều Khúc', NULL, '422', '30', '24',62),
       ('Lô 1-4, số 431', 'Tam Trinh', NULL, '375', '27', '24',63),
       ('nan', 'nan', NULL, '596', '39', '24', 64),
       ('298', 'Cầu Diễn', NULL, '437', '31', '24', 65),
       ('18', 'Hữu Nghị', NULL, '885', '52', '24', 66),
       ('KCN Bình Phú', 'nan', NULL, '760', '47', '24',66),
       ('13-15', 'Lê Thánh Tôn', NULL, '351', '25', '24',67),
       ('1', 'Xốm', NULL, '452', '32', '24',68),
       ('235', 'Hoàng Quốc Việt', NULL, '429', '31', '24',69),
       ('nan', 'nan', NULL, '752', '46', '24', 69),
       ('Km25', 'Quốc lộ 6', NULL, '528', '36', '24',70),
       ('Tòa nhà Đại học Đông Đô, 60B', 'Nguyễn Huy Tưởng', NULL, '423', '30', '24',70),
       ('Khu Giáo dục và Đào tạo – Khu Công nghệ cao Hòa Lạc – Km29', 'Đại lộ Thăng Long', NULL, '777', '47', '24',71),
       ('3', 'Cầu Giấy', NULL, '391', '28', '24', 72),
       ('Km9', 'Nguyễn Trãi', NULL, '474', '34', '24',73),
       ('8', 'Bùi Xuân Phái', NULL, '471', '34', '24',74),
       ('Tòa nhà A21, Viện Hàn Lâm Khoa học và Công nghệ Việt Nam, 18', 'Hoàng Quốc Việt', NULL, '330', '24', '24',75),
       ('29A, Ngõ 124', 'Vĩnh Tuy', NULL, '365', '26', '24',76),
       ('456', 'Minh Khai', NULL, '365', '26', '24',77),
       ('218', 'Lĩnh Nam', NULL, '383', '27', '24',77),
       ('207', 'Giải Phóng', NULL, '364', '26', '24',78),
       ('Số 59, ngõ 230', 'Ỷ La', NULL, '443', '32', '24',79),
       ('Km10', 'Nguyễn Trãi', NULL, '423', '30', '24',80),
       ('43', 'Trần Duy Hưng', NULL, '333', '24', '24',81),
       ('nan', 'Quốc Lộ 21', NULL, '511', '36', '24',82),
       ('87', 'Nguyễn Chí Thanh', NULL, '391', '28', '24',83),
       ('18', 'Phố Viên', NULL, '427', '31', '24',84),
       ('Nhà B101', 'Nguyễn Hiền', NULL, '363', '26', '24',85),
       ('360', 'La Thành', NULL, '394', '28', '24',86),
       ('42', 'Yết Kiêu', NULL, '347', '25', '24',87),
       ('91', 'Chùa Láng', NULL, '391', '28', '24',88),
       ('28A', 'Lê Trọng Tấn', NULL, '438', '32', '24',89),
       ('371', 'Nguyễn Hoàng Tôn', NULL, '426', '31', '24',90),
       ('nan', 'Nguyễn Trác', NULL, '441', '32', '24',91),
       ('171', 'Trung Kính', NULL, '334', '24', '24',92),
       ('Số 4', 'Ngõ Chùa Hưng Ký', NULL, '369', '26', '24',92),
       ('Khu Văn hóa nghệ thuật Mai Dịch', 'nan', NULL, '329', '24', '24',93),
       ('136', 'Xuân Thủy', NULL, '328', '24', '24',94),
       ('Số 18, Ngõ 55', 'Trần Phú', NULL, '449', '32', '24',95),
       ('nan', 'nan', NULL, '529', '36', '24',96),
       ('nan', 'nan', NULL, '635', '41', '24',97),
       ('136 -138', 'Phạm Văn Đồng', NULL, '433', '31', '24',97),
       ('31', 'Dịch Vọng Hậu', NULL, '327', '24', '24',97),
       ('41A', 'Phú Diễn', NULL, '437', '31', '24',98),
       ('nan', 'Nghiêm Xuân Yêm', NULL, '371', '27', '24',99),
       ('nan', 'Quốc lộ 32', NULL, '565', '38', '24',100),
       ('98', 'Phố Dương Quảng Hàm', NULL, '332', '24', '24',101),
       ('nan', 'Đường 131 thôn Đạc Tài', NULL, '741', '46', '24',101),
       ('6', 'Vĩnh Phúc', NULL, '326', '23', '24',101),
       ('6', 'Nguyễn Phi Khanh', NULL, '819', '50', '24',101),
       ('175', 'Tây Sơn', NULL, '401', '28', '24',102),
       ('79', 'Hồ Tùng Mậu', NULL, '329', '24', '24',103),
       ('418', 'La Thành', NULL, '394', '28', '24',104),
       ('55', 'Giải Phóng', NULL, '364', '26', '24',105),
       ('1', 'Tôn Thất Tùng', NULL, '389', '28', '24',106),
       ('1A', 'Đức Thắng', NULL, '427', '31', '24',107);
