name: Deploy to Docker Hub

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        id: version
        run: |
          echo "VERSION=$(grep 'uniportal.api.version=' src/main/resources/application.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push
        run: docker buildx build --platform linux/amd64 -t uniportal/uniportal:${{ env.VERSION }} . --push

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << EOF
            sudo docker pull uniportal/uniportal:${{ env.VERSION }}
            sudo docker stop uni-portal || true
            sudo docker rm uni-portal || true
            sudo docker run -d --name uni-portal -p 443:8080 uniportal/uniportal:${{ env.VERSION }}
          EOF